### ISSUE TITLE
Unable to get postcss-global-data to work with postcss-custom-media in Next.js

### ISSUE THREAD

**Issue by ianyoung** [csstools/postcss-plugins#1001]
I've been unable to get `postcss-global-data` working with `postcss-custom-media` in a Next.js project. I've written a [StackOverflow post describing the issue](https://stackoverflow.com/questions/76439439/using-postcss-global-data-with-next-js). Is there something I'm missing or is this a bug?

**Comment by romainmenke** [comment]
Hi @ianyoung,

Thank you for reaching out.

Can you try changing the plugin order?

--------

From the plugin readme :

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-global-data

> It is important that [PostCSS Global Data](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-global-data) is used before the plugin that actually needs the data.

**Comment by ianyoung** [comment]
Hi @romainmenke . I just tried the same thing and to my surprise it worked! 

I missed that line in the docs. It could be worth putting that in bold emphasising it in some way.

Thanks for the super quick response and support. Much appreciated.

**Comment by romainmenke** [comment]
Happy that that worked!

Making that one line bold would make it harder to spot the lines above and below which also contain important information :)

Please do open issues when something isn't clear or isn't working.
We do take this feedback in mind and always look for ways to improve the documentation for all.

**Comment by ianyoung** [comment]
I wasn't really sure where to post since things have all been merged. I ran through all the documentation but was unable to get things working so I didn't know if it was a bug or something I wasn't doing correctly. It turned out to be the latter but it's still useful to be able to ask a question somewhere that's related to the codebase.

**Comment by romainmenke** [comment]
Opening an issue here is always a good way to reach out.

We always watch this space and we don't mind answering all questions :)
