### ISSUE TITLE
Link to changelog of dependencies from changelogs

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [csstools/postcss-plugins#1002]
### What would you want to propose?

Dependency updates are already listed, with the version number and the severity of the change (not sure if that's the right word), but if you want to know what the changes are you have to look the dependencies up manually.

### Suggested solution

Turn each listed dependency into a link to that dependency, and the version number into a link to the changelog for that dependency.

For example, in the latest postcss-preset-env release:
* Updated [`@csstools/postcss-relative-color-syntax`](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-relative-color-syntax) to [`1.0.2`](https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-relative-color-syntax/CHANGELOG.md) (patch)

### Additional context

Aside from just curiosity, I have a habit of including a brief summary of changes whenever I update a tool or library we use. This would save me a bunch of time, especially for larger releases :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Thank you @ehoogeveen-medweb for opening an issue about this 🎉 

These entries are already largely generated, so should be straightforward to add :

https://github.com/csstools/postcss-plugins/blob/de99109c5a2881864892849e9d255a4f8ebfe7bf/.github/bin/release-plan/release-plan.mjs#L127-L147

Please feel free to open a pull request if you have time.

**Comment by ehoogeveen-medweb** [comment]
@romainmenke How do you actually run it in a way that causes it to update the changelog?

I tried checking out https://github.com/csstools/postcss-plugins/commit/2009d84a1d0030374c392b81590a338792032a09 which comes right before https://github.com/csstools/postcss-plugins/commit/b8294e221db9690e41c541afc2a5305cd0b747f7 (which updates the `postcss-preset-env` changelog), then running `npm run release-plan`, but it just says `Nothing to release`. Is there something I need to do first?

**Comment by romainmenke** [comment]
🤔 yes, we should document this better.

----

You can add this in any plugin Changelog:

```
### Unreleased (patch)

- dummy change
```

**Comment by ehoogeveen-medweb** [comment]
Thanks! Yes, I think the existing `--dry-run` is a bit *too* dry, haha.

I still don't really understand how to get it to actually add things to the changelog - if I add `### Unreleased` to a changelog it does get converted to a new release, but it doesn't seem to be updating any of its dependencies or adding updates for them.

Of course, the process does error out eventually because I'm not logged into `https://registry.npmjs.org/`. Is it stopping too early because of that?

**Comment by romainmenke** [comment]
I've added some interrupts when a `DEBUG=true` env variable is set.

`DEBUG=true npm run release-plan`

I've also added some internal docs on what the release plan stuff is and how it works :

https://github.com/csstools/postcss-plugins/tree/main/.github/bin/release-plan#release-plan

-----

To trigger the update changelog feature :

- go to `packages/css-tokenizer/CHANGELOG.md`
- add `### Unreleased (patch) ...` to that changelog
- run `DEBUG=true npm run release-plan`

You should then see a bunch of files being updated.

**Comment by romainmenke** [comment]
@ehoogeveen-medweb I've updated all the changelog entries and added the id to the links :

https://github.com/csstools/postcss-plugins/commit/50e2c48d9525162d80922f719d76e5cf9065420d

Thank you again for suggesting this and for doing all the underlying work 🙇
