### ISSUE TITLE
Update vscode extension to support new nesting syntax

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-plugins#1007]
### What would you want to propose?

Currently the vscode extension doesn't support the new nesting syntax which make `@nest` obsolete.

Before with `@nest`:

![CleanShot 2023-06-21 at 11 48 35](https://github.com/csstools/postcss-plugins/assets/10454741/88c95bf5-fec2-4243-b55f-49e48fd7425e)

Now:

![CleanShot 2023-06-21 at 11 47 27](https://github.com/csstools/postcss-plugins/assets/10454741/1c48ed6a-4235-4c2b-9dea-dccc9957a1d4)

### Suggested solution

nested code is highlighted correctly without `@nest`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @equinusocio,

Thank you for reaching out.

Which VSCode extension?

----

Did you also try the native CSS support in VSCode, we contributed improved support for standard CSS nesting there and it landed in the latest release of VSCode.

**Comment by equinusocio** [comment]
https://marketplace.visualstudio.com/items?itemName=cpylua.language-postcss

Assuming this is coming from this team since it says `csstools` as the author.

> Did you also try the native CSS support in VSCode, we contributed improved support for standard CSS nesting there and it landed in the latest release of VSCode.

Nope, not yet.

**Comment by equinusocio** [comment]
sorry, pasted the wrong link:
https://marketplace.visualstudio.com/items?itemName=csstools.postcss

**Comment by romainmenke** [comment]
I've never personally contributed to that package/repo and it doesn't seem maintained anymore :/

I've been focussing my efforts on making sure that VSCode itself has really good support for CSS as that helps more people :)

The main difference at this point is likely support for `@custom-selector` and `@custom-media`.

**Comment by equinusocio** [comment]
By reading the extension reviews, there are issues with vs code intellisense, so it may be a good idea to remove the extension from the marketplace or deprecate it.

**Comment by romainmenke** [comment]
> so it may be a good idea to remove the extension from the marketplace or deprecate it.

I agree but beyond my control here :)
Ok if we close this here?

**Comment by Antonio-Laguna** [comment]
It's also beyond my control for what is worth. Only Jon can do it

**Comment by romainmenke** [comment]
I also opened this issue in that repo to map out what can be ported to the builtin VSCode support for CSS : https://github.com/csstools/postcss-language/issues/16

**Comment by romainmenke** [comment]
Going to close this here, we can follow up in the extension's repo.
