### ISSUE TITLE
packages provide wrong types under node16 module resolution

### ISSUE THREAD

**Issue by not-my-profile** [csstools/postcss-plugins#1031]
## node16 from ESM: type errors

Using the packages from [Deno](https://deno.land/) with TypeScript leads to type errors, but these errors can also be observed with `tsc` and Node.JS when using the new node16 module resolution:

```
$ npm i postcss-nesting
$ echo '{"type": "module"}' > package.json
$ echo "import postcssNesting from 'postcss-nesting'; postcssNesting();" > example.ts
$ tsc example.ts --moduleResolution node16 --lib es2020
example.ts:1:47 - error TS2349: This expression is not callable.
  Type 'typeof import("/tmp/example/node_modules/postcss-nesting/dist/index")' has no call signatures.

1 import postcssNesting from 'postcss-nesting'; postcssNesting();
                                                ~~~~~~~~~~~~~~
```

## node16 from CJS: runtime error

```
$ npm i postcss-nesting
$ echo '{"type": "commonjs"}' > package.json
$ echo "import postcssNesting from 'postcss-nesting'; postcssNesting();" > example.ts
$ tsc example.ts --moduleResolution node16 --lib es2020
$ node example.js
/tmp/example/example.js:4
(0, postcss_nesting_1.default)();
                              ^

TypeError: (0 , postcss_nesting_1.default) is not a function
    at Object.<anonymous> (/tmp/example/example.js:4:31)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.14.2
```

## What to do

As [Are the types wrong? explains](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md):

> A golden rule of declaration files is that if they represent a module—that is, if they use import or export at the top level—they must represent exactly one JavaScript file. They especially cannot represent JavaScript files of two different module formats.

So the `exports` like the following are wrong since they provide one `types` for both ESM and CJS:

https://github.com/csstools/postcss-plugins/blob/aaf88074689f64fdca1db391fffc5f3c337ef2da/plugins/postcss-nesting/package.json#L39-L46

Unfortunately `@rollup/plugin-typescript` like apparently most other build tools does not supporting correctly emitting different type definitions for ESM and CJS.

(Note that the [Are the types wrong?](https://arethetypeswrong.github.io/?p=postcss-nesting%4011.3.0) website currently wrongly doesn't report the node16 From CJS problem [since it doesn't yet perform type checking](https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/10)).

**Comment by romainmenke** [comment]
Hi @not-my-profile,
Thank you for reaching out about this.

Unfortunately this is impossible for us to solve.
This is an upstream problem.

As package authors we need tools to do this thing :
- author code in TypeScript and ES Modules
- transpile out to plain JS and ES Modules
- transpile out to plain JS and commonjs
- emit types for plain JS and ES Modules
- emit types for plain JS and commonjs

No such tool exists.

You can report this issue either with TypeScript or with Rollup.

-----

If however such a tool does exist, please let us know.
We are happy to change our setup to make this possible.

**Comment by not-my-profile** [comment]
Thanks for the quick reply! I see. Yeah I think this currently hangs at microsoft/TypeScript#54593.

**Comment by CobyPear** [comment]
Hi. I just ran into this issue as well.

> No such tool exists.

I believe [`tsup`](https://github.com/egoist/tsup/releases/tag/v7.2.0) as of the latest version (7.2.0) does a good job at making hybrid cjs and esm bundles with proper types.
Happy to look into contributing this change but I would need to find some time.

**Comment by CobyPear** [comment]
@romainmenke I think that's the world we live in right now in the TypeScript/Node ecosystem: pain for the end user because the package emits the wrong stuff, or pain for the maintainer to emit the right stuff.

I understand wanting a more robust solution to do this by default but I had thought in the past the TS team said they didn't want to deal with this issue and it was up to the ecosystem to make ESM, CJS, and TypeScript play nicely. [Maybe all that's needed for your libs is `esModuleInterop` set to true?](https://www.typescriptlang.org/docs/handbook/modules/appendices/esm-cjs-interop.html#applications-with-commonjs-code-should-always-enable-esmoduleinterop)

**Comment by romainmenke** [comment]
I think I currently have a good grasp on the complexity of this issue.
As I see it now :

1. default exports/imports work differently in commonjs and es modules. They also work differently in typings for commonjs and es modules. Emitting types for anything default exports will be broken when dual publishing.
2. rollup has a good hack for default exports when transpiling to commonjs. This hides any issues at runtime. TypeScript isn't aware that this hack is happening, so the types do not match the actual code after transpiling to commonjs.
3. TypeScript looks in `package.json` for `"type": "module"` to decide if it should output commonjs or es modules code. There is no way to set this programmatically. So it is impossible to make TypeScript the driver without messing with your `package.json`.
4. rollup only supports es modules and although it can output commonjs it doesn't have the right internals to process code end to end as commonjs. So it is impossible to let TypeScript output commonjs and then feed that to rollup for further processing.
5. Modern TypeScript with a modern config expects file extensions in import statements. When dual publishing while transpiling from es modules TypeScript to commonjs and es modules JavaScript you simply do not know what the file extensions will be. So you can not have working imports of other `.d.ts` files.

----------------

Issues 1-4 are unsolvable by us.
We can switch to another build tool, but I've tried a few and you essentially get a different mix of issues.

But issues 1-4 go away when you stop dual publishing typings.
We can still do dual publishing of runtime code and simply omit types for commonjs.

-----------

Issue 5 can be solved by bundling types into a single `.d.ts` file.
