### ISSUE TITLE
Plugins for `@supports` and `@container` equivalent to `postcss-custom-media`

### ISSUE THREAD

**Issue by universse** [csstools/postcss-plugins#1035]
### What would you want to propose?

Right now, we can write this
```css
@custom-media --tablet (48rem <= width < 64rem);
```

Would be cool if we can do the same for `@container` and `@supports`.

### Suggested solution

Maybe new plugins

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by aaronstezycki** [comment]
I'm not 100% sure about the OP question, but possibly he might mean can we adapt custom media queries to work with @container queries. A huge win, and means we don't have to define another set of variables to work with containers. 

ie.

```
@custom-media --tablet (48rem <= width < 64rem);

@container (--tablet) { ... }

```

**Comment by romainmenke** [comment]
Hi @aaronstezycki,

That would be a question/suggestion for the CSS specification editors :)

These PostCSS plugins follow the specification.

**Comment by romainmenke** [comment]
Going to close this for now because it isn't actionable for us until there is at least a draft specification :)

Please file a new issue later or ask us to re-open later if a specification emerges and we miss it 🙇

**Comment by elliottmangham** [comment]
This would be really great for us 👍

We widely use `@container` queries and it is a shame not being able to access our `@custom-media` presets that work well with `@media` queries.
