### ISSUE TITLE
[Feature] Add support for Container Queries (the next generation responsive technology)

### ISSUE THREAD

**Issue by lwyj123** [csstools/postcss-plugins#104]
## Background
Container Queries (@container) is the new responsive design syntax. details can be found in https://www.youtube.com/watch?v=dhrX_biPH8c

polyfill: https://github.com/jsxtools/cqfill

## Change
I think we can simply add `cqfill` into the package and use it directly.

**Comment by aminimalanimal** [comment]
fwiw, that polyfill (cqfill) has apparently fallen out of date as the specs have adjusted. Noticed this in [a recent CSS-Tricks article](https://css-tricks.com/a-new-container-query-polyfill-that-just-works/). They note that this one is up to date: https://github.com/GoogleChromeLabs/container-query-polyfill.

**Comment by romainmenke** [comment]
I think this is best kept outside of `postcss-preset-env` as it the polyfill runs fully on the client.


@Antonio-Laguna Maybe we can add it to cssdb?
That will make it more discoverable for users who go to cssdb.

**Comment by Antonio-Laguna** [comment]
@romainmenke it's already within CSSDB. I should probably remove cqfill from CSSDB though: https://cssdb.org/#container-queries

**Comment by romainmenke** [comment]
Then I think we can close this one here?
Nothing much to do for us on this feature :/

**Comment by Antonio-Laguna** [comment]
Closing this as this has been removed from CSSDB and given this is a fully JS polyfill we can't inject it through Prest Env
