### ISSUE TITLE
Support exponential functions

### ISSUE THREAD

**Issue by nickmccurdy** [csstools/postcss-plugins#1043]
### What would you want to propose?

Exponential functions (stage 2 on [cssdb](https://cssdb.org/#exponential-functions)) ([spec](https://www.w3.org/TR/css-values-4/#exponent-funcs)) adds several helpful functions for exponentiation in `calc()` formulae:

- [`pow()`](https://www.w3.org/TR/css-values-4/#funcdef-pow)
- [`sqrt()`](https://www.w3.org/TR/css-values-4/#funcdef-sqrt)
- [`hypot()`](https://www.w3.org/TR/css-values-4/#funcdef-hypot)
- [`log()`](https://www.w3.org/TR/css-values-4/#funcdef-log)
- [`exp()`](https://www.w3.org/TR/css-values-4/#funcdef-exp)

They're currently only supported in Firefox and Safari.

### Suggested solution

I suggest we either add a plugin supporting this or leverage an existing one (like [`postcss-calc`](https://github.com/postcss/postcss-calc)) to compile these functions to JS or other `calc()` functions. After that work is complete, we could extend support to more browsers in `postcss-preset-env`.

### Additional context

I often find myself reaching for [modular scales](https://www.modularscale.com/), which one one of many helpful use cases of exponents in design. I could also see potential use cases in calculating values based off the golden ratio / Fibonacci series and displaying log-normal distributions.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @nickmccurdy,
Thank you for this feature request!

We already have support for these functions in `css-calc` : https://preset-env.cssdb.org/blog/css-calc-v1.0.0/

So a PostCSS plugin for these functions should be relatively easy to add.

**Comment by romainmenke** [comment]
All math functions

- [ ] abs
- [ ] acos   postcss-trigonometric-functions
- [ ] asin   postcss-trigonometric-functions
- [ ] atan   postcss-trigonometric-functions
- [ ] atan2  postcss-trigonometric-functions
- [ ] calc
- [ ] clamp  postcss-clamp
- [ ] cos    postcss-trigonometric-functions
- [ ] exp    postcss-exponential-functions
- [ ] hypot  postcss-exponential-functions
- [ ] log    postcss-exponential-functions
- [ ] max
- [ ] min
- [ ] mod    postcss-stepped-value-functions
- [ ] pow    postcss-exponential-functions
- [ ] rem    postcss-stepped-value-functions
- [ ] round  postcss-stepped-value-functions
- [ ] sign
- [ ] sin    postcss-trigonometric-functions
- [ ] sqrt   postcss-exponential-functions
- [ ] tan    postcss-trigonometric-functions

**Comment by nickmccurdy** [comment]
Cool, `css-calc` sounds like it would make things much easier. It seems like all the unchecked functions (not just exponential) are supported, so hopefully we could just make a new plugin supporting all `calc()` functions by copying `postcss-trigonometric-functions` and replacing its function list with `mathFunctionNames`. Does this sound look a good idea?

**Comment by romainmenke** [comment]
Although we have a single package `css-calc` that is able to solve math expressions, it is preferable in our setup to have multiple PostCSS plugins for distinct features or sets of features.

The different plugins align with the groups of functions that browsers have implemented.

`exponential` functions for example are still missing from Chrome for example while `trigonometric` functions have been implemented. (https://cssdb.org/#exponential-functions)

------

A single plugin for everything `calc` wouldn't be ideal because it's a moving target.

If a new math function is added (e.g. `mix()`) then we need to redefine the support targets, which technically is a breaking change.

-----

I've created a new plugin for the exponential functions here : https://github.com/csstools/postcss-plugins/pull/1044

**Comment by nickmccurdy** [comment]
> If a new math function is added (e.g. `mix()`) then we need to redefine the support targets, which technically is a breaking change.

I'm curious what you mean by this. I'm not aware of anything that isn't back compatible, as arbitrary function names in CSS aren't allowed, and two standardized specs wouldn't introduce two functions with the same name.

**Comment by romainmenke** [comment]
There are plugin options like [`minimumVendorImplementations`](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#minimumvendorimplementations) that are tied to the definition of features and plugins.

Some users might configure `postcss-preset-env` to only transpile features that are fairly certain to be stable. Those with a minimum of 2 implementations.

Example scenario :

- we create a new plugin `postcss-calc-transpile` that does everything related to maths in CSS
- today this covers the list mentioned in a previous comment
- at least 2 vendors implement the entire group of features and the plugin matches `minimumVendorImplementations: 2`
- tomorrow we add support for a new `mix` function that has zero or one implementations

At that point in time users with `minimumVendorImplementations: 2` would no longer have transpilation for any other feature from this `postcss-calc-transpile` plugin, as the plugin is disabled by `postcss-preset-env`.

This would be a breaking change as suddenly their CSS that depends on this plugin wouldn't be transpiled any more.

------

_Any plugin that isn't intended to be a part of `postcss-preset-env` doesn't have this constraint and those can be broad and can have changing definitions._

**Comment by nickmccurdy** [comment]
I see, that's making sense now, thanks. Would it be possible to solve this by moving the selection of functions into configuration that `postcss-preset-env` could manage, or is it only able to enable and disable entire plugins?

**Comment by romainmenke** [comment]
Hi @nickmccurdy,


[`postcss-exponential-functions`](https://www.npmjs.com/package/@csstools/postcss-exponential-functions) is now are latest plugin and it is part of `postcss-preset-env` version `9.1.0`

Thank you again for requesting this feature.
