### ISSUE TITLE
inset-inline-end: 0; gets stripped with direction options

### ISSUE THREAD

**Issue by styurenkov-b2broker** [csstools/postcss-plugins#1056]
### Bug description

```css
.element {
  inset-inline-end: 0;
}
```

if in the pipe i dont use any options :
```js
                .pipe(
                    postcss([
                        postcssLogical({})
                        ])
                 )
```

it is built as `.element { right: 0 }`

if in the pipe i use options :
```js
                .pipe(
                    postcss([
                        postcssLogical({
                             blockDirection: "right-to-left",
                            inlineDirection: "top-to-bottom",
                        })
                        ])
                 )
```

it is built as `.element {}` and the property is stripped

### Source CSS

```css
.element {
  inset-inline-end: 0;
}
```

### Expected CSS

```css
.element { right: 0 }
```

OR

```css
.element { left: 0 }
```

### Actual CSS

```
.element { }
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### Extra config

```js
            .pipe(plumber())
            .pipe(
                scss({
                    outputStyle: "compressed",
                })
            )
            .pipe(
                autoprefixer({
                    overrideBrowserslist: ["last 3 versions"],
                })
            );
```

### What plugin are you experiencing this issue on?

gulp pipeline

### Plugin version

7.0.0

### What OS are you experiencing this on?

macOS

### Node Version

18.9.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @styurenkov-b2broker,
Thank you for reaching out.

Is this setup correct?

https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiIuZWxlbWVudCB7XG4gIGluc2V0LWlubGluZS1lbmQ6IDA7XG59IiwiY29uZmlnIjp7ImJyb3dzZXJzIjpbIj4gMC4yJSBhbmQgbm90IGRlYWQiXSwibWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyI6MCwic3RhZ2UiOjIsImxvZ2ljYWwiOnsiaW5saW5lRGlyZWN0aW9uIjoiYm90dG9tLXRvLXRvcCIsImJsb2NrRGlyZWN0aW9uIjoicmlnaHQtdG8tbGVmdCJ9fX0%3D

**Comment by styurenkov-b2broker** [comment]
@romainmenke it seems i misused the options a bit. 
I need both options to be right-to-left, is there a way to achieve this?

```
blockDirection: "right-to-left",
inlineDirection: "right-to-left"
```

I get the error: 
`Error: [postcss-logical] "blockDirection" and "inlineDirection" must be on separate axes`

in our case we position both blocks and text in rtl style, not just text.

**Comment by romainmenke** [comment]
Is it possible that you intended this config :

```
inlineDirection: "right-to-left",
blockDirection: "top-to-bottom",
```

**Comment by romainmenke** [comment]
Why do you need both to be `right-to-left` ?

`inline` and `block` are always different directions in browsers, it wouldn't make sense to allow this option.

**Comment by romainmenke** [comment]
> in our case we position both blocks and text in rtl style, not just text.

`block` direction is not for blocks and `inline` is not for text :)

They are both directions for all elements : https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values#block_vs._inline

**Comment by styurenkov-b2broker** [comment]
@romainmenke 

in my case it causes unexpected behavior: 

if I use 
```
inlineDirection: "right-to-left",
blockDirection: "top-to-bottom",
```

some elements that change their position on hover behave unexpectedly. 
I have relatively positioned elements, that appear from side on parent hover. (expected to appear from left to right or from right to left).  instead of being built to "left:" or "right:" they are built to "top:" or "bottom:"

if I use it other way round:
```
inlineDirection: "top-to-bottom",
blockDirection: "right-to-left",
```

It also instead of being built to "left:" or "right:" they are built to "top:" or "bottom:"

So based on that I thought i need both options to be rtl. Because it works correctly without any options, but with options it gets built to "top:" or "bottom:" while I expect "left:" or "right:"

**Comment by styurenkov-b2broker** [comment]
**in short, again.** any options result it to be built as "top:0"
without options its built as "left:0"

**Comment by romainmenke** [comment]
Can you provide a reproduction?

Both HTML and CSS?

Then we can test this in a browser with and without the transforms.

----

At this time I am thinking that you have a bug in your CSS/HTML and that the plugin is fine, but I might be wrong and having a reproduction allows me to verify this :)

**Comment by romainmenke** [comment]
These options give you left/right :
- [left](https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiIuZWxlbWVudCB7XG4gIGluc2V0LWlubGluZS1lbmQ6IDA7XG59IiwiY29uZmlnIjp7ImJyb3dzZXJzIjpbIj4gMC4yJSBhbmQgbm90IGRlYWQiXSwibWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyI6MCwic3RhZ2UiOjIsImxvZ2ljYWwiOnsiaW5saW5lRGlyZWN0aW9uIjoicmlnaHQtdG8tbGVmdCIsImJsb2NrRGlyZWN0aW9uIjoiYm90dG9tLXRvLXRvcCJ9fX0%3D)
- [right](https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiIuZWxlbWVudCB7XG4gIGluc2V0LWlubGluZS1lbmQ6IDA7XG59IiwiY29uZmlnIjp7ImJyb3dzZXJzIjpbIj4gMC4yJSBhbmQgbm90IGRlYWQiXSwibWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyI6MCwic3RhZ2UiOjIsImxvZ2ljYWwiOnsiaW5saW5lRGlyZWN0aW9uIjoibGVmdC10by1yaWdodCIsImJsb2NrRGlyZWN0aW9uIjoiYm90dG9tLXRvLXRvcCJ9fX0%3D)

**Comment by styurenkov-b2broker** [comment]
@romainmenke 

problem solved. sorry, it seems i was building a wrong gulp tasks unrelated to this file + confused by readme file. 
settings blocks direction to top to bottom and setting inline direction to ltr or rtl builds correctly now. 

Consider changing default example in package readme. 
Right now it suggest to set blocks to rtl and inline to top to bottom. 

While now I understand, it's an unrelated to real language example. 
At first I thought it's the correct default options for RTL languages.

**Comment by romainmenke** [comment]
Glad to hear that!

----

> While now I understand, it's an unrelated to real language example,
at first I thought it's the correct default options for RTL languages.

We already mention this :

> You might want to tweak these values if you are using a different writing system, such as Arabic, Hebrew or Chinese for example.

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical#:~:text=You%20might%20want%20to%20tweak%20these%20values%20if%20you%20are%20using%20a%20different%20writing%20system%2C%20such%20as%20Arabic%2C%20Hebrew%20or%20Chinese%20for%20example.

Maybe we need to change it to :

**You should tweak these values so that they are specific to your language, such as Arabic, Hebrew or Chinese for example.**

(and place it in bold)

**Comment by romainmenke** [comment]
I've made the wording a bit stronger so that hopefully fewer people will stumble over this : https://github.com/csstools/postcss-plugins/commit/273ced57ce8cd17da2003dd22e356bb9795b9a07

Thank you again for opening an issue about this!
It is always very valuable to hear about these points of friction with our tools 🙇
