### ISSUE TITLE
Unexpected `Unknown feature` warning

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-plugins#1061]
Hello, I'm **disabling** the [`oklab-function`](https://preset-env.cssdb.org/features/#oklab-function) in my config, and recently I'm getting a warning that the feature doesn't exist. It's suggesting to use [`lab-function`](https://preset-env.cssdb.org/features/#lab-function) which is a different one.

```
[next:dev] (1:1) postcss-preset-env: Unknown feature: "postcss-oklab-function", did you mean: "lab-function"
```

My postcss config:

```js
import postcssMixins from 'postcss-mixins';

{
  plugins: {
    'postcss-import': {},
    'postcss-replace': {
      pattern: /token\(.*?--([^\s]+?)\)/gi,
      data: tokens,
    },
    'postcss-preset-env': {
      stage: 0,
      features: {
        'logical-properties-and-values': false,
        'prefers-color-scheme-query': false,
        'postcss-oklab-function': false,
        'gap-properties': false,
        'cascade-layers': false,
      },
      insertAfter: {
        'custom-media-queries': postcssMixins,
      },
    },
    'postcss-mixins': {},
    cssnano: {
      preset: [
        'default',
        {
          discardComments: {
            removeAll: true,
          },
        },
      ],
    },
  }
}
```
I'm getting this warning in every file where I use `oklch` colors

![CleanShot 2023-07-28 at 15 47 36](https://github.com/csstools/postcss-plugins/assets/10454741/982f65ee-dff5-4fee-aeaa-3c3a7fb3e5c6)

**Comment by romainmenke** [comment]
Hi @equinusocio,

You can find the feature name here : https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md

The feature name is : `oklab-function`

_I will need to check if we can make it suggest that correctly._

-----


You should move `'postcss-mixins': {},` up in your config.

It's better to have non-standard features first, even with PostCSS 8 and later.

-----

`prefers-color-scheme-query` This won't be enabled by default in recent versions of `postcss-preset-env`, so you can remove this override.

**Comment by romainmenke** [comment]
@equinusocio,

I am also a bit curious why you are disabling the `oklch` plugin.

Is there a specific issue you encountered?

**Comment by equinusocio** [comment]
Because we don't want the following transformation:

```css
.test-oklab {
	color: oklab(40% 0.001236 0.0039);
}

.test-oklch {
	color: oklch(40% 0.268735435 34.568626);
}

/* becomes */

.test-oklab {
	color: rgb(73, 71, 69);
	color: color(display-p3 0.28515 0.27983 0.27246);
}

.test-oklch {
	color: rgb(131, 28, 0);
	color: color(display-p3 0.49163 0.11178 0.00000);
}
```

`oklch` and `color()` are supported by all our targetted browsers and we want to keep them as they are without bloating the output. 

We write `rgb`, `oklch`, or any other color formats only when we need it. Also, I find that `color(display-p3 1 0 0)` is hard to read when debugging.

This is a recent struggle I have had with preset-env, I find myself disabling most of the modern features polyfills because they are supported and the extra generated code is useless for our users (eg. `prefers-color-scheme-query`, `logical-properties-and-values` and `postcss-color-mix`).

As postcss and preset-env user since 2015, I sometimes think the time to remove it is near the corner.

**Comment by equinusocio** [comment]
the above is an old configuration i'm fixing. Then I'll update it because I think there is no need to disable features manually. We just use browserslist. I guess the following will work:

```js
  plugins: {
    'postcss-mixins': {},
    'postcss-import': {},
    'postcss-replace': {
      pattern: /token\(.*?--([^\s]+?)\)/gi,
      data: tokens,
    },
    'postcss-preset-env': {},
    cssnano: {
      preset: [
        'default',
        {
          discardComments: {
            removeAll: true,
          },
        },
      ],
    },
  },
```

**Comment by romainmenke** [comment]
```js
 plugins: {
    // make it a single stylesheet first
    'postcss-import': {},
    // string-level find/replace second
    'postcss-replace': {
      pattern: /token\(.*?--([^\s]+?)\)/gi,
      data: tokens,
    },
    // non-standard scss like things
    'postcss-mixins': {},
    // polyfills and transpiling
    'postcss-preset-env': {},
    // minifier
    cssnano: {
      preset: [
        'default',
        {
          discardComments: {
            removeAll: true,
          },
        },
      ],
    },
  },
```

**Comment by equinusocio** [comment]
by renaming the feature it works. Thanks!

**Comment by romainmenke** [comment]
You're welcome!

Thank you for reporting this.
We've released a new version that will suggest multiple feature names when something unknown is entered.

That should make it easier to get unstuck :)
