### ISSUE TITLE
Why not support node17, only support 16 and 18

### ISSUE THREAD

**Issue by misakichan** [csstools/postcss-plugins#1069]
### Bug description

When I try to install @csstools/selector-specificity@2.2.0, I get an error
` @csstools/selector-specificity@2.2.0: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || >=18". Got "17.9.1"
`

But our project is developed based on node17, is there any better solution? 

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Selector Not

### Plugin version

2.2

### What OS are you experiencing this on?

Windows

### Node Version

17.9.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @misakichan 

Node 17 is no longer supported by node itself.
We support node LTS versions for much longer than non-LTS versions.
14, 16, 18, 20, ... are all LTS versions.

see : https://nodejs.dev/en/about/releases/

------

You typically do not want to base your project on non-LTS versions.

LTS versions will guarantee a much longer period of security related patches for your stack.

-----

Is it possible to update to node 18?

**Comment by romainmenke** [comment]
Hi @misakichan,

Did that answer your questions?
