### ISSUE TITLE
Add `flexbox gap` support

### ISSUE THREAD

**Issue by lwyj123** [csstools/postcss-plugins#107]
flexbox gap is in Working Draft, https://www.w3.org/TR/css-align-3/#gaps.

Below is the polyfill:
https://github.com/limitlessloop/flex-gap-polyfill

**Comment by romainmenke** [comment]
@lwyj123 Thank you for opening this issue.
Looking at that polyfill it has a number of serious limitations : https://github.com/gavinmcfarland/flex-gap-polyfill#known-limitations

This is fine if you manually add that package and first read the docs.

If we add this feature to `postcss-preset-env` most users won't first read the docs and will be surprised that that this plugin can break CSS that worked before.

We do want to be able to provide fallbacks for as much features as possible but we try to make sure these are as pure as possible.
