### ISSUE TITLE
Incorrect peer dependency "@csstools/css-tokenizer@^2.2.0"

### ISSUE THREAD

**Issue by ckhatton-transreport** [csstools/postcss-plugins#1116]
### Environment

```text
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 74.94 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 7.29.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Edge: 113.0.1774.57
    Safari: 16.5.1
  npmPackages:
    nuxt: ^2.17.1 => 2.17.1 
```

### Reproduction

`yarn install --check-files`

### Describe the bug

When `yarn` does an install or checks the files, it reports:

> "nuxt > @nuxt/webpack > postcss-preset-env > postcss-custom-media > @csstools/cascade-layer-name-parser@1.0.4" has incorrect peer dependency "@csstools/css-tokenizer@^2.2.0"

### Additional context

Over on the [`nuxt` repo ticket](https://github.com/nuxt/nuxt/issues/23117), it is reckoned this is a `postcss-preset-env` issue.

### Logs

```shell-script
❯ yarn install --check-files
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "aws-amplify > @aws-amplify/core > react-native-url-polyfill@1.3.0" has unmet peer dependency "react-native@*".
warning "aws-amplify > @aws-amplify/analytics > @aws-sdk/client-firehose > @aws-sdk/middleware-retry > react-native-get-random-values@1.9.0" has unmet peer dependency "react-native@>=0.56".
warning "nuxt > @nuxt/webpack > postcss-preset-env > postcss-custom-media > @csstools/cascade-layer-name-parser@1.0.4" has incorrect peer dependency "@csstools/css-tokenizer@^2.2.0".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
✨  Done in 8.76s.
```

**Comment by romainmenke** [comment]
Hi @ckhatton-transreport,

I can't see from your report which version it has and which version it thinks it should have instead.

Is it possible that your package manager updated `@csstools/cascade-layer-name-parser` but didn't update `@csstools/css-tokenizer` or the other way around?

That would just be a bug in your package manager (in this case `yarn`).
I think this might a relevant bug report in yarn : https://github.com/yarnpkg/yarn/issues/4986

Can you try updating everything?
Even transitive dependencies.

I don't use yarn so I don't know the exact steps to fix this issue.

**Comment by ckhatton-transreport** [comment]
Hey @romainmenke, thanks for your input.

Well I had previously updated everything in the hope to shake off the warning.

I am unsure what it exactly means by "has incorrect peer dependency"; whether it is the wrong version or a completely wrong package pair. I can force a version via the "resolutions" part of the `package.json` (it is how I've fixed the security issues yarn reports in the audit) but I can't make it use a different package (I think it is down to the module import of `@csstools/cascade-layer-name-parser`).

From what I can see from the `yarn.lock` file is `@csstools/css-tokenizer` _is_ using `2.2.0`.

I wonder if this really is a `@csstools/cascade-layer-name-parser` issue.

**Comment by romainmenke** [comment]
I am 100% sure that there is nothing wrong with our packages :)

`yarn` also works with a fresh install:
- no node_modules dir
- no lock file

I've added a new e2e test to specifically test that everything works with `yarn`.

This test passes without any issues or warnings : https://github.com/csstools/postcss-plugins/pull/1119

<img width="792" alt="Screenshot 2023-09-13 at 11 08 07" src="https://github.com/csstools/postcss-plugins/assets/11521496/f5f0d240-f770-482e-88ba-10e2804ae8a4">

**Comment by ckhatton-transreport** [comment]
Ok, thank you for checking that out. I would have a guess it is an issue of `@csstools/cascade-layer-name-parser`, as it would make sense that that is what is importing the package `@csstools/css-tokenizer`; so I will try knocking on their door.

I just tried forcing a lower version of `@csstools/css-tokenizer` using the resolution `"nuxt/**/@csstools/cascade-layer-name-parser/@csstools/css-tokenizer": "^2.1.1"`, and it didn't remove the warning.

**Comment by ckhatton-transreport** [comment]
I just realised it is a tool of `postcss-plugins` 😂 🤦

Oh well, I guess this is a dead end then 😅

**Comment by romainmenke** [comment]
> I guess this is a dead end then

No it's not a dead end :)

We will do a fresh release of some of the dependencies to make sure that `yarn` works, even when it's broken.

My point was that this is a `yarn` issue and that you can likely help yourself through some `yarn` specific steps. I don't use `yarn` so I don't know the specific magic incantation :)

**Comment by romainmenke** [comment]
@Antonio-Laguna there are two packages that still need a release :

```
;npm run release-plan:dry-run

> @csstools/postcss-plugins@1.0.0 release-plan:dry-run
> node .github/bin/release-plan/release-plan.mjs --dry-run

Current npm user does not have write access for postcss-custom-media
Current npm user does not have write access for postcss-custom-selectors
Nothing to release
```

If/when you have time, could you push these out?
This will help users of `yarn` who find themselves stuck as described above.

**Comment by romainmenke** [comment]
Hi @ckhatton-transreport,

We just published a fresh release of everything.
If you update `postcss-preset-env` your issue should be resolved.

If you still get an error, please let us know, then we will investigate further.
Thank you again for reporting this 🙇
