### ISSUE TITLE
Add `postcss-normalize-display-values`

### ISSUE THREAD

**Issue by Semigradsky** [csstools/postcss-plugins#112]
https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-display-values

> Normalize display property values with PostCSS.
> ### Input
> 
> ```css
> div {
>     display: inline flow-root
> }
> ```
> 
> ### Output
> 
> ```css
> div {
>     display: inline-block
> }
> ``` 

Spec: https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by Antonio-Laguna** [comment]
After checking with CSSnano maintainers they will be merging this into the library as opposed to keeping maintaining it so we'll be replicating this into our plugins.
