### ISSUE TITLE
Error: [postcss-custom-media] "importFrom" is no longer supported

### ISSUE THREAD

**Issue by ravindasenarath** [csstools/postcss-plugins#1131]
I had to upgrade libraries of a project I was working on and while doing that `postcss-custom-media` library was updated to `10.0.1` from `7.0.8`. 

Project had a `postcss.config.js` file like following

```
module.exports = {
  plugins: {
    'postcss-nested': {},
    'postcss-custom-media': {
      importFrom: [
        {
          customMedia: { '--m': '(min-width: 640px)' }
        },
        ,
        {
          customMedia: { '--t': '(min-width: 980px)' }
        }
      ]
    }
  }
}
```

Now I got the error
`Error: [postcss-custom-media] "importFrom" is no longer supported`
I tried many sytax from internet but nothing worked. How this can be solved.
Thanks

**Comment by romainmenke** [comment]
Hi @ravindasenarath,

This is explained in detail here : https://github.com/csstools/postcss-plugins/discussions/192

There are many alternatives listed there.
Hopefully that helps?

------

Very brief recap :

- `postcss-custom-media` is a polyfill for a proposed standard CSS feature
- the `importFrom` sub-feature isn't standard at all, it's a hack to fix issues in other tools like webpack
- the `importFrom` sub-feature was removed from all the plugins that are focussed on stadard CSS syntax features

You will need to migrate to other solutions.

**Comment by ravindasenarath** [comment]
Hi @romainmenke 

Used `postcss-custom-media-generator` and thought it did the trick. I'm not much of a UI person just had to upgrade the libraries so had to fix this one way or other. Thanks anyway.
