### ISSUE TITLE
Plugin for `light-dark()`

### ISSUE THREAD

**Issue by MrHBS** [csstools/postcss-plugins#1143]
### What would you want to propose?

A PostCSS plugin for `light-dark()` function added in `css-color-5`

### Suggested solution

```css
:root {
  —foo: light-dark(bar, baz);
}
```
becomes:
```css
:root {
  —foo: bar;
}

@media (prefers-color-scheme: dark) {
  :root {
    —foo: baz;
  }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @MrHBS,

Thank you for requesting this feature.

If I recall correctly the `light-dark()` function is tied to the `color-scheme` property, not the `prefers-color-scheme` media query : https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

We might be able to do this with a space toggle.

**Comment by romainmenke** [comment]
[You can see the difference between the property and media query in this ](https://drafts.csswg.org/css-color-adjust-1/#used-color-scheme)

> To determine the used color scheme of an element:
> If the user’s [preferred color scheme](https://drafts.csswg.org/css-color-adjust-1/#preferred-color-scheme), as indicated by the prefers-color-scheme media feature, is present among the listed [color schemes](https://drafts.csswg.org/css-color-adjust-1/#color-scheme), and is supported by the user agent, that’s the element’s [used color scheme](https://drafts.csswg.org/css-color-adjust-1/#used-color-scheme).
> 
> Otherwise, if the user has indicated an overriding preference for their chosen color scheme, and the [only](https://drafts.csswg.org/css-color-adjust-1/#valdef-color-scheme-only) keyword is not present in [color-scheme](https://drafts.csswg.org/css-color-adjust-1/#propdef-color-scheme) for the element, the user agent must [override the color scheme](https://drafts.csswg.org/css-color-adjust-1/#override-the-color-scheme) with the user’s [preferred color scheme](https://drafts.csswg.org/css-color-adjust-1/#preferred-color-scheme). See [§ 2.3 Overriding the Color Scheme](https://drafts.csswg.org/css-color-adjust-1/#color-scheme-override).
> 
> Otherwise, if the user agent supports at least one of the listed [color schemes](https://drafts.csswg.org/css-color-adjust-1/#color-scheme), the [used color scheme](https://drafts.csswg.org/css-color-adjust-1/#used-color-scheme) is the first supported color scheme in the list.
> 
> Otherwise, the [used color scheme](https://drafts.csswg.org/css-color-adjust-1/#used-color-scheme) is the browser default. (Same as [normal](https://drafts.csswg.org/css-color-adjust-1/#valdef-color-scheme-normal).)

------

A codepen to illustrate : https://codepen.io/romainmenke/pen/RwEEPEe

The `light-dark()` function must work in the same way as the webkit specific `-webkit-link` color.

So it is dark only when the element indicates that it supports a dark color scheme and when the user choses a dark color scheme.

**Comment by romainmenke** [comment]
It's fine to leave this open :)

I wasn't trying to say that we can't or won't do this.
Only that the proposed implementation wasn't going to be correct.

**Comment by romainmenke** [comment]
See : https://github.com/parcel-bundler/lightningcss/commit/808ce799c658f3fd435b7bf82a1c4f26aa60daf5

**Comment by romainmenke** [comment]
_awaiting releases_

**Comment by romainmenke** [comment]
Hi @MrHBS,

This has been released : https://www.npmjs.com/package/@csstools/postcss-light-dark-function
We will add it to `postcss-preset-env` in an upcoming release.

Thank you again for the feature request.
