### ISSUE TITLE
Output the targets/plugins used

### ISSUE THREAD

**Issue by dmnsgn** [csstools/postcss-plugins#115]
The `debug` option from babel preset env (https://babeljs.io/docs/en/babel-preset-env#debug) is particularly useful when using browsers and trying to understand which plugins are being used. 

I assume it would list which of these are used https://github.com/csstools/postcss-preset-env/blob/master/src/lib/plugins-by-id.js

**Comment by romainmenke** [comment]
@dmnsgn `postcss-preset-env` now supports setting `{ debug: true }` in the options.
This will output a lot of information about which plugins are enabled/disabled and why.
@Antonio-Laguna did all the work here!

**Comment by dmnsgn** [comment]
Thank you, very useful 👍
