### ISSUE TITLE
Annoying warning 'Please update to version 7...' when using version 9.2.0

### ISSUE THREAD

**Issue by Bonjour123** [csstools/postcss-plugins#1159]
### Bug description

Here is my package.json dev_dependencies:

    "postcss-preset-env": "^9.2.0",
    "postcss": "^8.4.24",

or pnpm-lock.yaml:

      postcss-preset-env:
        specifier: ^9.2.0
        version: 9.2.0(postcss@8.4.31)

### Actual Behavior

┌────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                                              │
│   This version of postcss-preset-env is not optimised to work with PostCSS 8.                                                   │
│                Please update to version 7 of PostCSS Preset Env.                                                                            │
│                                                                                                                                                                              │
│                    If you find issues, you can report it at:                                                                                               │
│          https://github.com/csstools/postcss-plugins/issues/new/choose                                                                  │
│                                                                                                                                                                               │
└──────────────────────────────────────────────────────────────────────┘

### Expected Behavior

No warning as requirement is already met

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

9.2.0

### What OS are you experiencing this on?

Ubuntu 22.04

### Node Version

v18.17.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @Bonjour123,

That message is only present in a single release of `postcss-preset-env` : `v6.7.1`.
It does not exist in the version you mention.

That you are still seeing this message means that somehow you still have `v6.7.1` installed and that you are using that version.

**Comment by Bonjour123** [comment]
My bad, you're completely right ! I was precss that was requiring it.

**Comment by romainmenke** [comment]
Glad that you found what was causing this :)
