### ISSUE TITLE
Postcss@8.4.31 with postcss-preset-env@7.8.3 compatibility issue

### ISSUE THREAD

**Issue by cds88** [csstools/postcss-plugins#1160]
Although I am using Postcss@8.4.31 with postcss-preset-env@7.8.3  I am still getting this error in the console: "This version of postcss-preset-env is not optimised to work with PostCSS 8 . Please update to version 7 of PostCss Preset Env "

Which versions of given packages should I use to get rid of this error ? 
current installed versions:
 - PostCsss@8.4.31
 - posttcss-preset-env@7.8.3
 - Node 18.3.0

**Comment by romainmenke** [comment]
Hi @cds88,

See : https://github.com/csstools/postcss-plugins/issues/1159

Only `postcss-preset-env` version `6.7.1` has this message.
This message does not exist in any other release.

That you are seeing this message means that you are somehow running `6.7.1`.

**Comment by cds88** [comment]
Thanks for reply. You are right,  I was using precss which had old version of postcss-preset-env in its dependencies. Removing the plugin seemed to fix the issue. Once again thanks for help and assistance.

**Comment by romainmenke** [comment]
Always happy to help 🙇
