### ISSUE TITLE
`@csstools/css-color-parser` does not expose that an `alpha` of `1` was set implicitly or explicitly 

### ISSUE THREAD

**Issue by bbugh** [csstools/postcss-plugins#1169]
Hello. 👋 For a project, I'm reviewing over a dozen color parsing libraries, all of which have various problems. css-color-parser is the best parser. However, it has one correctness issue that affects precise parsing.

**Problem**

`parseComponentValue` is incorrectly setting a default `alpha`, even if one is not specified in the parsed color value. 

For example:

```js
color(parseComponentValue(tokenize({ css: 'rgb(100, 100, 100)' })))
```

results in the following ColorData:

```json
{
  "colorNotation": "rgb",
  "channels": [
    0.39215686274509803,
    0.39215686274509803,
    0.39215686274509803
  ],
  "alpha": 1,
  "syntaxFlags": {}
}
```

While this alpha can be **inferred** to be 1, for tokenization and parsing, the alpha *has not been defined*. While it is true that they are equivalent in an rgb color *model*, at a parsing level they are not equivalent. By forcing a default alpha value, precision is lost in the parsing, and with it the ability to know what the actual input was.

For example, for precise converting, `#00f` should be `rgb(0 0 255)`, and `#00ff` should be `rgb(0 0 255 / 1)`. However, with the alpha value always as 1, it is indeterminate which value is the correctly precise conversion when parsing user input.

**Expectation**

Precise parsing would look like this:

```js
color(parseComponentValue(tokenize({ css: '#00f' })))
//> { colorNotation: "rgb", channels: [0, 0, 1], alpha: undefined }
```

```js
color(parseComponentValue(tokenize({ css: 'rgba(0, 0, 255, 1)' })))
//> { type: 'rgb', values: [0, 0, 255], alpha: 1 }
```

**Comment by romainmenke** [comment]
Hi @bbugh,

We could add a new `syntaxFlag` for this.

existing flags :
- `#f00` -> `Hex`
- `rgb(255, 0, 0)` -> `LegacyHSL`
- `red` -> `NamedColor`
- `rgb(255 0 0)` -> no flags

A new flag could be `ExplicitAlphaChannel` that would be set when an alpha channel was found during parsing.

It is however important to note that these flags and their exact behavior is poorly defined.

For example,
what are the flags for : `color-mix(in srgb, #f00, rgb(255, 0, 0))` ?

We use them to detect syntax difference in the whole value where it is more interesting to merge all the found flags.

We don't use them to determine the exact notation with the granularity that you are asking.

--------------

`css-color-parser` follows the CSS specification and there an omitted alpha is an exact equal to an explicit alpha of `1` in all cases with one exception.

In relative color syntax you can omit the alpha channel keyword and then the alpha of the reference color will be used instead.

`rgb(from rgb(255 0 0 / 10) r g b)` equals `rgb(255 0 0 / 10)`

--------------

Can you give a practical example where it is important to know the difference between implicit and explicit alpha of `1`?

Knowing the practical use case makes it easier for us to suggest a way forward.

**Comment by romainmenke** [comment]
```js
color(parseComponentValue(tokenize({ css: '#00f' })))
//> { colorNotation: "rgb", channels: [0, 0, 1], alpha: undefined }
```

_Forgot to answer this directly._

I don't like using JavaScript language details as part of the API surface.

`undefined` is not the same as `0` but `if (!foo.alpha) {}` would be true for both `undefined` and `0`. While `if (foo.alpha === 1)` would only be true for an explicit alpha.

This is not a good representation of what was actually parsed because an implicit alpha is equivalent to an alpha of `1` and running `if (foo.alpha) {}` or `if (foo.alpha == 1) {}` should be true.

The proposed change would break a lot of the internal logic but also could break the code of other users of this library.

**Comment by romainmenke** [comment]
@bbugh

Apparently I already added a flag for exactly this a while ago.
I kinda assumed you would have tested this and that there really wasn't a flag yet :)
And I forgot that I already implemented this.

```js
// does have the flag
assert.ok(color(parse('rgb(50% 0 0 / 1)')).syntaxFlags.has('has-alpha'));
assert.ok(color(parse('rgb(127, 0, 0, 1)')).syntaxFlags.has('has-alpha'));
assert.ok(color(parse('rgba(127, 0, 0, 1)')).syntaxFlags.has('has-alpha'));
assert.ok(color(parse('#f00f')).syntaxFlags.has('has-alpha'));

assert.ok(color(parse('rgb(50% 0 0 / 0)')).syntaxFlags.has('has-alpha'));
assert.ok(color(parse('rgb(127, 0, 0, 0)')).syntaxFlags.has('has-alpha'));
assert.ok(color(parse('rgba(127, 0, 0, 0)')).syntaxFlags.has('has-alpha'));
assert.ok(color(parse('#f000')).syntaxFlags.has('has-alpha'));

// does not have the flag
assert.ok(!color(parse('rgb(50% 0 0')).syntaxFlags.has('has-alpha'));
assert.ok(!color(parse('rgb(127, 0, 0)')).syntaxFlags.has('has-alpha'));
assert.ok(!color(parse('rgba(127, 0, 0)')).syntaxFlags.has('has-alpha'));
assert.ok(!color(parse('#f00')).syntaxFlags.has('has-alpha'));
```

So closing as this is already supported.

**Comment by bbugh** [comment]
Hi @romainmenke, you are absolutely right! Thank you for such a quick reply and thorough response.

I would have also assumed I would had seen that, especially since I spent a while with the library yesterday checking the functionality and then looking through the code to see what it would take to submit a PR. I remember the `SyntaxFlag` during parsing, but apparently it didn't occur to me that it might be available in `ColorData`. I guess it's like that video with the gorilla where nobody sees the gorilla. 🤦🏻‍♂️

This also solves the other problem I had, knowing whether the input was rgb/hsl level 3 (with commas) or level 4+ (no commas), and look there's syntax flags for `legacy-hsl` and `legacy-rgb`. 🎉

In case you're still curious, the use case that brought me here is building a GUI component for a client that has functionality that mimics the Shift+Click color mode selection on color swatches in the browser's Inspector developer tools. And since I'm already doing something similar, I'm planning to bring my [VSCode color mode transforming extension](https://github.com/bbugh/vscode-change-color-format) up to date as I've had a few requests for level 4 format. 

After going through so many color parsing libraries with so many unusable quality issues, it's fantastic to have a reliable baseline reference-quality one to work with. Thank you so much!

---

One note in case anyone comes across this in the future, the `syntaxFlags` map is `Set<SyntaxFlag>` where `SyntaxFlag` is an enum, so for TypeScript you'll have to explicitly reference the type:

```ts
import { 
  color, 
  type SyntaxFlag 
} from '@csstools/css-color-parser';

color.syntaxFlags.has(SyntaxFlag.HasAlpha)
```

**Comment by romainmenke** [comment]
> In case you're still curious, the use case that brought me here is building a GUI component for a client that has functionality that mimics the Shift+Click color mode selection on color swatches in the browser's Inspector developer tools. And since I'm already doing something similar, I'm planning to bring my [VSCode color mode transforming extension](https://github.com/bbugh/vscode-change-color-format) up to date as I've had a few requests for level 4 format.

Cool!

-----

There are two more cases that you might need to keep in mind:

### `color(srgb ....)`

`color(parse('color(srgb 1 0 0)'))`

This has the color notation set to `srgb`, not `rgb`.

```js
{
    colorNotation: 'srgb',
    channels: [ 1, 0, 0 ],
    alpha: 1,
    syntaxFlags: ['has-number-values']
}
```

### `var()` in `alpha`

`color(parse('rgb(1 0 0 / var(-foo))'))`

This has the syntax flag `has-variable-alpha`.
It's still possible to convert this to any other syntax because the `alpha` channel does not affect the conversion.

```js
{
    colorNotation: 'rgb',
    channels: [ 0.00392156862745098, 0, 0 ],
    alpha: FunctionNode {
      type: 'function',
      name: [ 'function-token', 'var(', 12, 15, { value: 'var' } ],
      endToken: [ ')-token', ')', 21, 21, undefined ],
      value: [
        TokenNode {
          type: 'token',
          value: [ 'ident-token', '--foo', 16, 20, { value: '--foo' } ]
        }
      ]
    },
    syntaxFlags: ['has-variable-alpha', 'has-number-values', 'has-alpha']
}
```

**Comment by bbugh** [comment]
Thanks so much for that!
