### ISSUE TITLE
Adding :is

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-plugins#117]
Does [`:is`](https://github.com/csstools/postcss-is-pseudo-class) plugin will be added to preset-env?

**Comment by romainmenke** [comment]
Notes :

- postcss-nesting has a good implementation of the logic behind `:is`
- css-has-pseudo has a good implementation of selector specificity matching

Extracting and combining those two bits should give a good `:is` transform.

**Comment by romainmenke** [comment]
@equinusocio We now have a plugin ready that we feel comfortable adding to preset-env

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-is-pseudo-class#readme

This is planned for the next minor version `7.3`

**Comment by equinusocio** [comment]
@romainmenke lovely

**Comment by romainmenke** [comment]
@equinusocio This has shipped in the latest version.
At the moment it is mainly good at splitting lists and handling specificity and less so with complex selectors.

Please let us know if you have any issues with or general feedback :)
