### ISSUE TITLE
How to use custom properties with postcss-relative-color syntax?

### ISSUE THREAD

**Issue by MrNightingale** [csstools/postcss-plugins#1226]
I'm trying to achieve next (similar to sass lighten function):

```
:root {
  --brand-primary: #ffe100;
  --brand-primary-lighter: hsl(from var(--brand-primary) h s calc(l + 0.1)); // I can't just use hex since `--brand-primary` is a dynamic value
  --brand-secondary: #2c2c2c;
}
```
it works properly in Chrome but older Safari and Firefox doesn't support relative color syntax. It works with `postcss-relative-color syntax` plugin but without custom property. I've tried to add also `postcss-custom-properties` plugin but didn't succeed.

my config
```
postcss: {
    plugins: {
      'postcss-custom-properties': {},
      '@csstools/postcss-relative-color-syntax': {},
    }
  }
```

Is `postcss-relative-color syntax` plugin support usage of custom properties or how to achieve what I need? Thanks in advance.

**Comment by romainmenke** [comment]
see : https://github.com/csstools/postcss-plugins/issues/1221

**Comment by romainmenke** [comment]
I've also added a note in the README to clarify that `var()` isn't supported :

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-relative-color-syntax

<img width="860" alt="Screenshot 2023-12-27 at 14 18 43" src="https://github.com/csstools/postcss-plugins/assets/11521496/972756a3-854d-4c59-93e3-9d1182c45a78">
