### ISSUE TITLE
Typos for package name in `@csstools/css-parser-algorithms` examples

### ISSUE THREAD

**Issue by ybiquitous** [csstools/postcss-plugins#1264]
Hi. I happened to find typos in the `@csstools/css-parser-algorithms` code examples. Maybe, the following seems correct:

```diff
-import { parseComponentValue } from '@csstools/css-parser';
+import { parseComponentValue } from '@csstools/css-parser-algorithms';
```

Search `@csstools/css-parser'`:
https://github.com/search?q=repo%3Acsstools%2Fpostcss-plugins+%22%40csstools%2Fcss-parser%27%22&type=code

Example:
https://github.com/csstools/postcss-plugins/blob/bf56313a00db7dfd8875039180060d9ddf6f01d1/packages/css-parser-algorithms/src/index.ts#L18

EDIT: If this is my misunderstanding, feel free to close it.

**Comment by romainmenke** [comment]
Good catch!

**Comment by romainmenke** [comment]
Thank you for reporting this @ybiquitous!
I've fixed the typos.

If there are things missing from the docs, please let us know.
Happy to add more examples and patterns.

**Comment by ybiquitous** [comment]
Wow, the fix is super fast. Thank you.

> Happy to add more examples and patterns.

Great to hear. I'm glad to report if I find missing stuff. 👍🏼
