### ISSUE TITLE
Ability to do negative numbers in Design Tokens.

### ISSUE THREAD

**Issue by blaquehat** [csstools/postcss-plugins#1272]
### What would you want to propose?

Add an option similar to unitsAndValues that does negative numbers. It would make it easier to switch the number instead of having to support a whole set just for negative measurement numbers.

### Suggested solution

Something like
`padding-bottom: design-token('size.spacing.medium-alias' to rem as negative);`

This would allow you to still change between rem and pixel with a negative number.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @blaquehat,

Why not write : `calc(-1 * design-token('size.spacing.medium-alias' to rem))` ?

I think that the existing tools in CSS for number manipulation are much more powerful than anything we could provide as a flag on the `design-token` function

**Comment by blaquehat** [comment]
Hi @romainmenke, 

Sounds good to me. Your solution makes a lot of sense.

Thank you!
