### ISSUE TITLE
If `tsconfig.json` is set to CommonJS mode, the declaration files cannot be read.

### ISSUE THREAD

**Issue by yuheiy** [csstools/postcss-plugins#1303]
### Bug description

If `tsconfig.json` is set to CommonJS mode, the declaration files for almost modules cannot be read.

`tsconfig.json`:

```json5
{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "Node10",
    "strict": true
  }
}
```

`test.ts`:

![スクリーンショット 2024-02-26 22 52 13](https://github.com/csstools/postcss-plugins/assets/11547305/72f2726b-52cd-430a-9792-a7a66f3a6c50)

The cause is probably that the `types` is not set in `package.json`.

```diff
	"main": "dist/index.cjs",
	"module": "dist/index.mjs",
+	"types": "dist/index.d.ts",
	"exports": {
		".": {
			"import": {
				"types": "./dist/index.d.ts",
				"default": "./dist/index.mjs"
			},
			"require": {
				"default": "./dist/index.cjs"
			}
		}
	},
```

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Plugin version

*

### Node Version

20

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @yuheiy,

This is not a bug, this is by design.
We do not provide types for commonjs, only for es modules.

The types we do have for es modules are only valid for the es modules source, not for the commonjs source.

See https://github.com/csstools/postcss-plugins/issues/1031#issuecomment-1848977339 for more context.

**Comment by romainmenke** [comment]
Thank you for checking out some tools @yuheiy,

At first glance `unbuild` doesn't seem to solve the hard problems and only works for projects that happen to have compatible JavaScript that can be easily transpiled between commonjs and es modules (https://github.com/unjs/unbuild/issues/374)

I tried `tshy` and it didn't work at all.
It also fails to solve the hard problems : https://github.com/isaacs/tshy?tab=readme-ov-file#handling-default-exports

-------

At this time I've kinda embraced this issue. Typings are a secondary feature and es modules is the future. So from our perspective it makes more sense to focus on providing the best dev experience for es modules while also having a correct runtime for commonjs.

**Comment by yuheiy** [comment]
Thank you for your explanation. Now that I understand what the problem is, I will close the issue.

**Comment by yuheiy** [comment]
Just so you know, I initially aimed to create a CommonJS (only) package using your module with tsc, specifically a PostCSS plugin. Given the issue, I've now decided to go with a bundler instead.
