### ISSUE TITLE
Add `project.json#types` to `postcss-preset-env/package.json`

### ISSUE THREAD

**Issue by raypatterson** [csstools/postcss-plugins#1342]
When using this plugin in a `postcss.config.*ts` file with TypeScript [`tsconfig.json#compilerOptions.moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) _not_ set to honor `package.json#exports` the import is `package.json#module` for which no `project.json#types` are provided.. 

This seems to fix the issue:

```diff 
# postcss-preset-env/package.json
{
    ...
    "main": "dist/index.cjs",
    "module": "dist/index.mjs",
+   "types": "./dist/index.d.ts",
```

**Comment by romainmenke** [comment]
Hi @raypatterson ,

That is not a bug.
We do not support types for commonjs.

see :
- https://github.com/csstools/postcss-plugins/issues/1031#issuecomment-1848977339
- https://github.com/csstools/postcss-plugins/issues/1303
- https://github.com/csstools/postcss-plugins/issues/1295
- https://github.com/csstools/postcss-plugins/issues/1217
- https://github.com/csstools/postcss-plugins/issues/1313
