### ISSUE TITLE
 Cannot find type definition file for 'postcss-preset-env'.

### ISSUE THREAD

**Issue by onlymetmh** [csstools/postcss-plugins#1350]
### Bug description

In my project, when I import postcss-preset-env using esModule, I encounter an error: "Cannot find type definition file for 'postcss-preset-env'. The file is in the program because: Entry point for implicit type library 'postcss-preset-env'."

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

9.5.3

### What OS are you experiencing this on?

Windows

### Node Version

16.20.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @onlymetmh,

That is not a bug.
We do not support types for commonjs.

see :
- https://github.com/csstools/postcss-plugins/issues/1031#issuecomment-1848977339
- https://github.com/csstools/postcss-plugins/issues/1303
- https://github.com/csstools/postcss-plugins/issues/1295
- https://github.com/csstools/postcss-plugins/issues/1217
- https://github.com/csstools/postcss-plugins/issues/1313
- https://github.com/csstools/postcss-plugins/issues/1342
