### ISSUE TITLE
HTML Select with "multiple" attribute leads to "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by HannesT117** [csstools/postcss-plugins#1365]
### Bug description

In https://github.com/csstools/postcss-plugins/blob/main/plugins/css-blank-pseudo/src/browser.js#L52, the code assumes that `element.selectedIndex` is always the index of an element in the options array. 

When using a select field with attribute `multiple`, [this index can be `-1` though](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedIndex). This leads to an `Uncaught TypeError: Cannot read properties of undefined (reading 'value')`

**Minimal Example**

```html
<!DOCTYPE html>
<html>
  <body>
    <select multiple="" required="">
      <option value="one">One</option>
      <option value="two">Two</option>
      <option value="three">Three</option>
    </select>

    <script src="https://unpkg.com/css-blank-pseudo@6.0.1/dist/browser-global.js"></script>
    <script>
      cssBlankPseudoInit();
    </script>
  </body>
</html>
```

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

CSS Blank Pseudo

### Plugin version

6.0.1

### Node Version

18

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @HannesT117,

Thank you for reporting this!

For this plugin we also have puppeteer tests.
Updating these with a failing test can be done here : https://github.com/csstools/postcss-plugins/blob/c13f67d1897d9024136c839afe6103d9394bda8b/plugins/css-blank-pseudo/test/_browser.html#L13-L38

**Comment by HannesT117** [comment]
Hi @romainmenke thanks for the info! I've extended the tests with a second select :)

**Comment by romainmenke** [comment]
This has been released!

Thank you again for reporting and fixing this issue 🙇
