### ISSUE TITLE
Add `@container` support to `@custom-media`

### ISSUE THREAD

**Issue by matthewgisonno** [csstools/postcss-plugins#1367]
### What would you want to propose?

Hello... We use `@custom-media` in our project starter kit... We are slowly making the switch from `@media` queries to `@container` queries.  Would like to see if there is the possibility for supporting `@container` in `@custom-media`.

### Suggested solution

I did some very quick testing.  It appears updating this line:

https://github.com/csstools/postcss-plugins/blob/d802bc9fd8eab0e6035b3816d7d6ff16c8cc8aef/plugins/postcss-custom-media/src/index.ts#L40

to be something like this:
```js
if (atRule.name.toLowerCase() !== 'media' && atRule.name.toLowerCase() !== 'container') {
```

Then allows the following to work:
```css
@custom-media --width-below650 (width < 650px);
```

Finally, in my component css:
```css
@container (--width-below650) {
  .innerWrapper {
    background-color: red;
  }
}
```

### Additional context

I don't mind putting a PR together or hoping this will at least get the conversation started 👍 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
see : https://github.com/csstools/postcss-plugins/issues/1035

**Comment by matthewgisonno** [comment]
> see : #1035

got it... makes sense...  I appreciate the information
