### ISSUE TITLE
postcss-custom-properties: `Found unknown node. Make sure to provided all involved nodes. Unknown node: "--content-inset-block-start"`

### ISSUE THREAD

**Issue by MarcWadai** [csstools/postcss-plugins#1377]
### Bug description

Since release postcss-custom-properties@^13.3.7 with postcss-loader 8.1.1, i have the error below when using webpack with this postcss plugin: 

```
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):\nError: Found unknown node. Make sure to provided all involved nodes. Unknown node: \"--content-inset-block-start\"
```

### Actual Behavior

Throw an error when starting the application 

### Expected Behavior

When using postcss-custom-properties@^13.3.5, with postcss-loader 8.1.0 i didn't have any error and the webpack config didn't change since then

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Plugin version

postcss-custom-properties 13.3.7

### Node Version

18.19.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@MarcWadai,
Thank you for filing this issue.

Can you also provide the CSS that is causing this issue?
Happy to fix this, but I need something I can test with.

**Comment by MarcWadai** [comment]
This is my webpack config :
```
                        {
                            loader: "postcss-loader",
                            ident: "postcss",
                            options: {
                                sourceMap: true,
                                postcssOptions: () => ({
                                    "plugins": [
                                        // Note that we use slightly different plugins for PostCSS.
                                        require("postcss-import")(),
                                        require("postcss-mixins")(),
                                        require("postcss-simple-vars")(),
                                        require("postcss-nested")(),
                                        require("postcss-easings")(),
                                        require("postcss-hexrgba")(),

                                        // It's important that this plugin is last otherwise we end
                                        // up with broken CSS.
                                        require("postcss-preset-env")({ stage: 3, browsers: "last 2 versions" }),
                                    ],
                                    "parser": "postcss-scss",
                                    "local-plugins": true,
                                }),
                            },
                        },
```

And the error is triggering at some theme files which only contains imports :
```
@import "../../../../res/css/_font-sizes.pcss";
@import "../../light/css/_paths.pcss";
@import "../../light/css/_fonts.pcss";
@import "../../light/css/_light.pcss";
@import "_light-high-contrast.pcss";
@import "../../light/css/_mods.pcss";
@import "../../../../res/css/_components.pcss";
@import url("highlight.js/styles/atom-one-light.min.css");

```

**Comment by romainmenke** [comment]
Thank you @MarcWadai,

I can get the same error in the playground : https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyLl9kcmF3ZXJfcHkzbHRfMjYlMjAlN0IlNUNuJTIwJTIwLS1oYW5kbGUtYmxvY2stc2l6ZSUzQSUyMDRweCUzQiU1Q24lMjAlMjAtLWhhbmRsZS1pbmxpbmUtc2l6ZSUzQSUyMDMycHglM0IlNUNuJTIwJTIwLS1oYW5kbGUtaW5zZXQtYmxvY2stc3RhcnQlM0ElMjB2YXIoLS1jcGQtc3BhY2UtNHgpJTNCJTVDbiUyMCUyMC0taGFuZGxlLWluc2V0LWJsb2NrLWVuZCUzQSUyMDBweCUzQiU1Q24lMjAlMjAtLWNvbnRlbnQtaW5zZXQtYmxvY2stc3RhcnQlM0ElMjBjYWxjKCU1Q24lMjAlMjAlMjAlMjB2YXIoLS1oYW5kbGUtaW5zZXQtYmxvY2stc3RhcnQpJTIwJTJCJTIwdmFyKC0taGFuZGxlLWJsb2NrLXNpemUpJTIwJTJCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHZhcigtLWhhbmRsZS1pbnNldC1ibG9jay1lbmQpJTVDbiUyMCUyMCklM0IlNUNuJTdEJTIyJTJDJTIyY29uZmlnJTIyJTNBJTdCJTIyYnJvd3NlcnMlMjIlM0ElNUIlMjIlM0UlMjAwLjAwMDIlMjUlMjIlNUQlMkMlMjJtaW5pbXVtVmVuZG9ySW1wbGVtZW50YXRpb25zJTIyJTNBMCUyQyUyMnN0YWdlJTIyJTNBMiUyQyUyMmxvZ2ljYWwlMjIlM0ElN0IlMjJpbmxpbmVEaXJlY3Rpb24lMjIlM0ElMjJsZWZ0LXRvLXJpZ2h0JTIyJTJDJTIyYmxvY2tEaXJlY3Rpb24lMjIlM0ElMjJ0b3AtdG8tYm90dG9tJTIyJTdEJTJDJTIyZmVhdHVyZXMlMjIlM0ElN0IlMjJuZXN0aW5nLXJ1bGVzJTIyJTNBJTVCJTIyYXV0byUyMiUyQyU3QiUyMmVkaXRpb24lMjIlM0ElMjIyMDI0LTAyJTIyJTdEJTVEJTdEJTdEJTdE

(see the browser console)

**Comment by MarcWadai** [comment]
Thx for your quick answer. Yes i see it in the console..
But I really don't see where things are broken since the code didn't change, and I only did a `yarn install` which generated a new yarn lock with updated version (postcss 8.1.0 to 8.1.1)..
Do you have any idea where I could dig more ?

**Comment by MarcWadai** [comment]
Okay thx for your help ! for now i am just rolling back to postcss-loader 8.1.1 which is working fine :)

**Comment by romainmenke** [comment]
Hi @MarcWadai,

A fix for this issue has been applied and published.
