### ISSUE TITLE
`https://preset-env.cssdb.org/` not found

### ISSUE THREAD

**Issue by KAROTT7** [csstools/postcss-plugins#1440]
### Reproduction link

https://preset-env.cssdb.org/

### Bug description

Is this site no longer maintained?

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Plugin version

1.0.0

### What OS are you experiencing this on?

macOS

### Node Version

20.0.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
Thank you for reporting this @KAROTT7,

I was a bit too quick with updating a dependency of the site, which broke it.
I've added an extra step to the deploy script, to make sure that the site can build before we trigger a deploy. That should prevent future regressions.

Site is up again.
