### ISSUE TITLE
Error in package.json (`no-invalid-at-import-rules-when-bundling`)

### ISSUE THREAD

**Issue by AlexRMU** [csstools/postcss-plugins#1445]
### Bug description

The `parse-at-import.mjs` is not specified in the [files list](https://github.com/csstools/postcss-plugins/blob/56cc4544fbe04b431ec2337cd15f0ee59ffc2bac/plugins-stylelint/no-invalid-at-import-rules-when-bundling/package.json#L32), although it is being imported. Therefore, the plugin does not work.

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Plugin version

2.0.7

### Node Version

21

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@AlexRMU  Thank you for reporting this 🙇 

I wonder why our tests don't surface this 🤔

**Comment by romainmenke** [comment]
_I will publish a new release in a couple of days_

**Comment by romainmenke** [comment]
This has been published and should work better now @AlexRMU
Thank you again for reporting this.
We've added extra tests to prevent regressions.
