### ISSUE TITLE
"r.assign is not a function" error coming from postcss-logical

### ISSUE THREAD

**Issue by alebelcor** [csstools/postcss-plugins#147]
### Reproduction link

https://stackblitz.com/edit/nextjs-fx3c4g

### Bug description

It seems like the postcss-logical plugin is blowing up for me (for some reason) when I use the `transition` property in Next.js with CSS Modules.

### Actual Behavior

I see a `TypeError: r.assign is not a function` error on Next.js' dev overlay that is seemingly coming from `postcss-loader`.

The stacktrace in development is not very useful, but if I try to build I see this:

```
./src/components/Button/Button.module.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[
4].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[2]!./src/components/Button/Button.module.css
TypeError: r.assign is not a function
    at /Users/alebelcor/projects/test/src/components/Button/Button.module.css:12:3
    at W (/Users/alebelcor/projects/test/node_modules/postcss-logical/dist/index.cjs:1:7015)
    at /Users/alebelcor/projects/test/node_modules/postcss-logical/dist/index.cjs:1:11461
    at LazyResult.visitTick (/Users/alebelcor/projects/test/node_modules/next/node_modules/postcss/lib/lazy-result.js:456:16)
    at LazyResult.runAsync (/Users/alebelcor/projects/test/node_modules/next/node_modules/postcss/lib/lazy-result.js:372:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processImmediate (internal/timers.js:437:9)
    at async Span.traceAsyncFn (/Users/alebelcor/projects/test/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/alebelcor/projects/test/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js:46:22
    at async Span.traceAsyncFn (/Users/alebelcor/projects/test/node_modules/next/dist/trace/trace.js:74:20)
```

Which, to me, looks like it's coming from `postcss-logical`. Apologies if that's not the case.

If I comment out/remove the CSS line with the `transition` property the error goes away and everything works.

If I downgrade `postcss-preset-env` from `7.2.0` to `6.7.0` the error goes away and everything works.

### Expected Behavior

`postcss-logical` should not blow up when the `transition` property is used.

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### `npx` Output

I can't reproduce it like that. I get a `Cannot find module 'postcss'` error after trying.

Even after I try it in a project with `postcss` present in its `node_modules` folder.

### Extra config

`postcss.config.js`

```js
module.exports = {
  plugins: {
    'postcss-preset-env': {
      features: {
        'logical-properties-and-values': {
          dir: 'ltr',
        },
      },
    },
  },
};
```

### What plugin are you experiencing this issue on?

PostCSS Logical

### Plugin version

5.0.2

### Node Version

14.18.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@alebelcor Thank you for reporting this!

> I can't reproduce it like that. I get a Cannot find module 'postcss' error after trying.

Could you provide an example of `npx @csstools/csstools-cli postcss-logical`
Because that should work. `postcss` is bundled with the CLI.

`echo ".foo { padding-inline: 20px 40px; }" | npx @csstools/csstools-cli postcss-logical`

That works for me.

-----

_Looking at the real issue_

**Comment by Antonio-Laguna** [comment]
FWIW we've located it to be pinned to 8.2.15. See https://github.com/vercel/next.js/blob/aeb67cc28d1d589719b95043042c6cb8f9aab26c/packages/next/package.json#L79

**Comment by alebelcor** [comment]
@romainmenke @Antonio-Laguna Thank you for following up so quickly.

One thing I did, that I forgot to document, was that I was adding (the latest) `postcss` as a peer dependency as my understanding was that Next.js would use it instead of their compiled+bundled (outdated) version.

It seems that is unfortunately not the case, so for the time being I'm forced to disable that feature, i.e. logical properties

In light if this being more a Next.js-related issue, feel free to close this if deemed appropriate.

Thanks!

**Comment by romainmenke** [comment]
> One thing I did, that I forgot to document here, was that I was adding (the latest) postcss as a peer dependency as my understanding was that Next.js would use it instead of their compiled+bundled (outdated) version.

It would be very nice if nextjs would allow a broader range of dependency versions or other patterns (peer dependencies, dependency injection). Unfortunately they don't (yet).

As I can imagine this is an issue many are experiencing we want to do a small effort on our end to make all plugins managed here compatible with older versions of postcss.

We hope to roll this out soon!

We'll keep you posted on this and close this issue after.

Thank you again for reporting this and for providing enough detail so that we could figure out what was going on.

**Comment by romainmenke** [comment]
@alebelcor We just released updates for all plugins using features not supported in postcss `v8.2.x`.

Can you check if this now works for you?
