### ISSUE TITLE
Using align-content in block-level elements

### ISSUE THREAD

**Issue by xysccc** [csstools/postcss-plugins#1481]
### What would you want to propose?

Versions of chrome123 and above can now use align-content directly in a block-level element, but the postcss postcssPresetEnv plug-in now used in version 98 has no effect because align-content is originally a browser-supported attribute, but this attribute has no effect in block-level elements in versions before 123. If I still want to use align-content of block-level elements and make it effective in version 98, can I configure the plug-in?

### Suggested solution

Of course I can use flex or grid, but I just want to know if there is a solution in PostCSS Preset Env

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @xysccc,

I don't think there is a specific fallback we can generate with PostCSS that would be helpful.

With PostCSS we can't change browser behavior or give it new features.
We can only generate equivalents or good fallbacks.

Please let me know if there is such a good fallback :)
