### ISSUE TITLE
[postcss-nesting] After updating to v13, Vue's :deep() selector is not outputted correctly

### ISSUE THREAD

**Issue by deRaaf** [csstools/postcss-plugins#1496]
### Bug description

Probably because :is() is now used? When setting the edition back to 2021 css is outputted as expected.

### Source CSS

```
.card {
    :deep(.image-wrapper) {
        @apply h-[10.25rem];

        .image {
            @apply w-full h-full object-cover;
        }
    }
}
```

### Expected CSS

```
.card .image-wrapper {
    height: 10.25rem
}
.card .image-wrapper .image {
    height: 100%;
    width: 100%;
    -o-object-fit: cover;
       object-fit: cover
}
```

### Actual CSS

```
.card .image-wrapper {
    height: 10.25rem
}
:is(.card :deep(.image-wrapper)) .image {
    height: 100%;
    width: 100%;
    -o-object-fit: cover;
       object-fit: cover
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Extra config

export default {
    plugins: {
        'tailwindcss/nesting': 'postcss-nesting',
        tailwindcss: {},
        autoprefixer: {}
    }
};

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

13.0.0

### What OS are you experiencing this on?

macOS

### Node Version

22.9.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
I think this is the same question as in this discussion: https://github.com/csstools/postcss-plugins/discussions/1474

Basically you need to desugar first and only transpile for older browsers last.

This is not something we can fix because the bug is not on our end.
The bugs are with vue.
