### ISSUE TITLE
Custom Properties preserve false not working?

### ISSUE THREAD

**Issue by AlejandroPerezMartin** [csstools/postcss-plugins#1539]
### Bug description

Upon checking https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-properties I realised that the output for preserve false is the same as above.

If you see [this link](https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTNBcm9vdCUyMCU3QiU1Q24lMjAlMjAtLWNvbG9yJTNBJTIwYmxhY2slM0IlNUNuJTdEJTVDbiU1Q24uYm9keSUyMCU3QiU1Q24lMjAlMjBjb2xvciUzQSUyMHZhcigtLWJsYWNrKSUzQiU1Q24lN0QlMjIlMkMlMjJjb25maWclMjIlM0ElN0IlMjJicm93c2VycyUyMiUzQSU1QiUyMiUzRTk5Ljk5JTI1JTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTQlMkMlMjJzdGFnZSUyMiUzQTAlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCUyQyUyMmZlYXR1cmVzJTIyJTNBJTdCJTIybmVzdGluZy1ydWxlcyUyMiUzQSU1QiUyMmF1dG8lMjIlMkMlN0IlMjJlZGl0aW9uJTIyJTNBJTIyMjAyNC0wMiUyMiU3RCU1RCU3RCUyQyUyMnByZXNlcnZlJTIyJTNBZmFsc2UlN0QlN0Q=)

You can also see it's not swapping the variables.

### Source CSS

```css
:root {
  --color: black;
}

.body {
  color: var(--black);
}
```

### Expected CSS

```css
:root {
  --color: black;
}

.body {
  color: black;
}
```

### Actual CSS

```css
:root {
  --color: black;
}

.body {
  color: var(--black);
}
```

### Playgound example

https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTNBcm9vdCUyMCU3QiU1Q24lMjAlMjAtLWNvbG9yJTNBJTIwYmxhY2slM0IlNUNuJTdEJTVDbiU1Q24uYm9keSUyMCU3QiU1Q24lMjAlMjBjb2xvciUzQSUyMHZhcigtLWJsYWNrKSUzQiU1Q24lN0QlMjIlMkMlMjJjb25maWclMjIlM0ElN0IlMjJicm93c2VycyUyMiUzQSU1QiUyMiUzRTk5Ljk5JTI1JTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTQlMkMlMjJzdGFnZSUyMiUzQTAlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCUyQyUyMmZlYXR1cmVzJTIyJTNBJTdCJTIybmVzdGluZy1ydWxlcyUyMiUzQSU1QiUyMmF1dG8lMjIlMkMlN0IlMjJlZGl0aW9uJTIyJTNBJTIyMjAyNC0wMiUyMiU3RCU1RCU3RCUyQyUyMnByZXNlcnZlJTIyJTNBZmFsc2UlN0QlN0Q=

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

PostCSS Custom Properties

### Plugin version

14.0.4

### Node Version

20.17.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
You have a typo in your source:

```diff
:root {
  --color: black;
}

.body {
-   color: var(--black);
+   color: var(--black);
}
```

See: https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTNBcm9vdCUyMCU3QiU1Q24lMjAlMjAtLWNvbG9yJTNBJTIwYmxhY2slM0IlNUNuJTdEJTVDbiU1Q24uYm9keSUyMCU3QiU1Q24lMjAlMjBjb2xvciUzQSUyMHZhcigtLWNvbG9yKSUzQiU1Q24lN0QlMjIlMkMlMjJjb25maWclMjIlM0ElN0IlMjJicm93c2VycyUyMiUzQSU1QiUyMklFJTIwMTAlMjIlNUQlMkMlMjJtaW5pbXVtVmVuZG9ySW1wbGVtZW50YXRpb25zJTIyJTNBMCUyQyUyMnN0YWdlJTIyJTNBMiUyQyUyMmxvZ2ljYWwlMjIlM0ElN0IlMjJpbmxpbmVEaXJlY3Rpb24lMjIlM0ElMjJsZWZ0LXRvLXJpZ2h0JTIyJTJDJTIyYmxvY2tEaXJlY3Rpb24lMjIlM0ElMjJ0b3AtdG8tYm90dG9tJTIyJTdEJTdEJTdE

**Comment by AlejandroPerezMartin** [comment]
thanks for the quick response @romainmenke! and sorry I didn't notice it

![homer-simpson-from-the-simpsons-is-standing-in-a-grassy-field](https://github.com/user-attachments/assets/0ee2e21e-e119-47fe-9047-d76bfc2c1304)
