### ISSUE TITLE
[css-calc]: `acos()`, `asin()`, `atan()` and `atan2()` does not return angles with `deg`

### ISSUE THREAD

**Issue by asamuzaK** [csstools/postcss-plugins#1544]
### Bug description

``` javascript
import { calc } from '@csstools/css-calc';

console.log(calc('acos(-1)'));
// 3.1415926535898rad
// expected: 90deg

console.log(calc('asin(-1)'));
// -1.5707963267949rad
// expected: -90deg

console.log(calc('atan(1)'));
// 0.7853981633974rad
// expected: 45deg

console.log(calc('atan2(1s, 1000ms)'));
// 0.7853981633974rad
// expected: 45deg
```

Ref: https://drafts.csswg.org/css-values-4/#trig-funcs

> The angle returned by asin() must be normalized to the range [-90deg, 90deg]; the angle returned by acos() to the range [0deg, 180deg]; and the angle returned by atan() to the range [-90deg, 90deg].

### Source CSS

See above.

### Expected CSS

See above.
Returns angle with `deg`.

### Actual CSS

See above.
Returns angle with `rad`.

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### Plugin version

2.1.0

### What OS are you experiencing this on?

Windows

### Node Version

22.12.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @asamuzaK,

The specification only describes that the values should be normalized to a specific range and return type, it doesn't dictate the specific return unit. It does describe the expected range with the `deg` unit, but it doesn't dictate that values must be returned with this `deg` unit.

Both `rad` and `deg` should be fine and accepted as both are of type `<angle>`.

------

If you do want to normalize to the "canonical" unit for a given type you can set the `toCanonicalUnits` flag.

```js
console.log(calc('acos(-1)', { toCanonicalUnits: true }));
// 180deg

console.log(calc('asin(-1)', { toCanonicalUnits: true }));
// -90deg

console.log(calc('atan(1)', { toCanonicalUnits: true }));
// 45deg

console.log(calc('atan2(1s, 1000ms)', { toCanonicalUnits: true }));
// 45deg
```

Do note that `acos(-1)` is `180` degrees and not `90` as in your comment.

**Comment by asamuzaK** [comment]
> If you do want to normalize to the "canonical" unit for a given type you can set the toCanonicalUnits flag.

Got it.

> Do note that acos(-1) is 180 degrees and not 90 as in your comment.

Thanks for your feedback. My implementation should be wrong for acos().

**Comment by asamuzaK** [comment]
Just for a note:

``` javascript
console.log(calc('acos(-1.5)', {
  toCanonicalUnits: true
}));
// calc(NaN * 1rad)
```

**Comment by romainmenke** [comment]
You can also set `censorIntoStandardRepresentableValues: true`

Which will result in : `NaNdeg`.
As a string this is invalid CSS, but the parsed data, before serialization, is more useful.

Using `calcFromComponentValues()` instead of `calc()` allows you to inspect the resulting token as raw data. There you will find a token with a `NaN` value and a unit of `deg`.

**Comment by asamuzaK** [comment]
Thank you for the detailed explanation.

What I want is `calc(NaN * 1deg)` similar to the [wpt](https://github.com/web-platform-tests/wpt/blob/master/css/css-values/acos-asin-atan-atan2-serialize.html#L26) and the browser output.
As far as I've tested, calc() always returns in the form `calc(NaN * 1rad)`, so it's fine for me as I can simply replace the unit.

Thanks anyway.
It's a great tool.
