### ISSUE TITLE
Code re-use between packages

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#179]
Some plugins need the same bits of code.
Currently we copy/paste these bits between packages.

factors to consider :

- node 12/14 support when building in CI
- we do not want to publish these bits on npm
- rollup needs to bundle this and not treat it like an external dependency
- we need good documentation so that contributors can easily find parts they need

---------------

This is focused solely on code that needs to be available in plugins when they run.
Code/packages that are local to this repo have different requirements.

**Comment by romainmenke** [comment]
It is not possible to preserve node 12/14 support for building packages while at the same time having typescript support and reusing code :/

Maybe we do need a public tools/utils package?

**Comment by Antonio-Laguna** [comment]
Why can't we do what the new tape does? What am I missing

**Comment by romainmenke** [comment]
The new tape is called from regular js and executed by node.

The shared code for plugins trips up typescript when the plugin code is transpiled.
Typescript doesn't like it when importing files from outside the root dir :/

**Comment by Antonio-Laguna** [comment]
We can definitely have a public tools/util package though :)

**Comment by romainmenke** [comment]
At the moment we are balancing relative paths for code that isn't published and creating new packages for code that is complex and shared over multiple packages.

I think we can close this as "solved" for now.
