### ISSUE TITLE
Deprecate and republish plugins with names starting with `css-`

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#186]
see : https://github.com/csstools/postcss-plugins/pull/182#discussion_r789421151

These do not follow the naming guidelines and seemingly are not used much as direct dependencies.

Deprecating and republishing could go hand in hand with a more thorough cleanup and refactor.

**Comment by ehoogeveen-medweb** [comment]
Some inconsistencies I noticed regarding these:
* `css-has-pseudo` and `css-prefers-color-scheme` ship with all their files minified; `css-blank-pseudo` does not.
* `css-prefers-color-scheme` ships with `browser.min.js` but this file is identical to `browser.js` (as both are minified).

I don't really have an opinion about whether they should be minified or not (being able to read the code is nice if something goes wrong but these polyfills should be pretty much invisible anyway) but they should probably be consistent :)
