### ISSUE TITLE
Make `postcss-preset-env` processable by Webpack

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#221]
Currently you can't bundle `postcss-preset-env` with Webpack (and probably other bundlers)
This is not something we currently support or test for.

But it should also be low effort to get it working.
Needs investigating first.

- [x] what is wrong now? -> inconsistencies in plugins
- [x] can we have tests for this without adding too much bloat? -> kinda

**Comment by z0h3** [comment]
Thanks for your help! Waiting for updates.

**Comment by romainmenke** [comment]
@z0h3 We have found some inconsistencies in plugins and `package.json` files.
When we fixed those Webpack builds started working : https://github.com/csstools/postcss-plugins/pull/222

It is however important to note that we can't consider bundling through Webpack a feature of `postcss-preset-env`.

At the moment `postcss-preset-env` is considered a final product and intended to be used as-is. 

We will try to keep Webpack bundling supported and added tests for this.
If it breaks in a future update we will note this in the change logs.

We'll keep you updated on releases for these fixes.

**Comment by z0h3** [comment]
Great job!

**Comment by romainmenke** [comment]
@z0h3 All packages have been released.
Can you check if this now works for you?

**Comment by z0h3** [comment]
I confirm. Now it works correctly.
