### ISSUE TITLE
Add `oklab()` and `oklch()` colors support

### ISSUE THREAD

**Issue by ai** [csstools/postcss-plugins#225]
### What would you want to propose?

OKLab is better than Lab/LCH in blue. Apple and [W3C](https://www.youtube.com/watch?v=dOsp6u4bIwI) love it and Safari TP already supports it.

### Suggested solution

Maybe we should wait for a little, but let’s start to track OKLab early. If it goes good we can add it to `postcss-preset-env` to help W3C in their project of bringing new era of colors to CSS.

### Additional context

cc @svgeesus

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Is it possible that neither MDN or caniuse have entries for these yet or am I overlooking these?

They are next on my list after : https://github.com/csstools/postcss-plugins/pull/226

Complete list for `css-color-4` :
- [x] `rebeccapurple`
- [x] color functional notation (space separated)
- [x] `hwb()`
- [x] `color()`
- [x] `lab()`
- [x] `lch()`
- [x] gamut mapping
- [ ] `oklab()`
- [ ] `oklch()`

Gamut mapping also doesn't have any tracking yet in MDN or caniuse.

**Comment by ai** [comment]
> Is it possible that neither MDN or caniuse have entries for these yet or am I overlooking them?

PR was openned https://github.com/Fyrd/caniuse/issues/6124

**Comment by Antonio-Laguna** [comment]
Blocking since we can't do much yet. I assume the answer is no but does it make sense to separate the features, or will we be getting parity support so both features are supported at the same time?

**Comment by romainmenke** [comment]
If they don't ship at the same time we should separate them.
But this is highly unlikely.

Converting `lab` to `lch` is trival and so is `oklab` to `oklch` :
https://www.w3.org/TR/css-color-4/#lch-to-lab

Which is why `lab` and `lch` also shipped at the same time.
One less plugin if we can combine them.

**Comment by Antonio-Laguna** [comment]
@romainmenke at the same time if they're separated on MDN CSSDB has the ability to check multiple things to consider full support.
