### ISSUE TITLE
Add `in color-space` syntax to gradients

### ISSUE THREAD

**Issue by ai** [csstools/postcss-plugins#233]
### What would you want to propose?

Safari TP already [got](https://twitter.com/argyleink/status/1490376117064065025) color space support for gradients:

```css
background: linear-gradient(in lch, blue, red);
```

### Suggested solution

This feature (but without `in X` syntax) was already implemented in [postcss-easing-gradients](https://github.com/larsenwork/postcss-easing-gradients) by @larsenwork.

Maybe we can start from that code.

### Additional context

This feature could be part of amazing colors refactoring going by @romainmenke.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
https://drafts.csswg.org/css-images-4/#linear-gradients

**Comment by romainmenke** [comment]
At @ai The pull request linked above will close this issue as fixed.
But that plugin on its own will be useless.

Hopefully I will have time for `color-mix` soon, then we can all have fancy new gradients.

**Comment by ai** [comment]
Looks amazing. I will promote it later, after some sort end of war. I can’t force myself to post any non-anti-war content 😓.
