### ISSUE TITLE
useful "zero config" for preset-env

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#238]
Have been thinking about the first interaction new users have with the plugin and was wondering if we can make "zero config" also the best practice setup for most use cases?

_at the moment this is just a random thought, will come back to this_

**Comment by Antonio-Laguna** [comment]
Though this is opinionated I had this same thought and kind of why I want the "perf" section, to better see how we could use this moving forward. My concern is that this is constantly in flux and hence, major releases every time.

**Comment by romainmenke** [comment]
Going to close this.

By now I realised that there are too many conflicting but equally valid ways to "tune" the plugins.

Making an opinionated "zero" config default would push my opinions and would not help all users.

We can better have good docs and guides.
