### ISSUE TITLE
More info to main page

### ISSUE THREAD

**Issue by ai** [csstools/postcss-plugins#254]
[Main page](https://preset-env.cssdb.org/) looks really awesome. But it is not really informational.

What questions visitor will have:

1. What is this site about?
2. What is `postcss-preset-env`?
3. Why should I use it?
4. Is it small “indie” tool or everyone is using it.

If we will answer this questions on the main page, it will improve conversion.

**Comment by Antonio-Laguna** [comment]
@ai just a heads up, I've moved this into the monorepo now. We've just finished moving the site here and I was closing the repo when I stumbled upon this. I'm glad that at least one screenshot remains.  I think the homepage could use some of that love! 

We will do our best!
