### ISSUE TITLE
Support nested options for CLI

### ISSUE THREAD

**Issue by Antonio-Laguna** [csstools/postcss-plugins#258]
As per https://github.com/csstools/postcss-plugins/blob/main/packages/base-cli/src/args.ts#L161

There's no support for passing nested options, this gets messy with OKLab plugin which has the `subfeatures.displayP3`

**Comment by romainmenke** [comment]
Can you give an example of you passed the plugin options?

I thought I tested this style :

```
echo ".test-lab { color: lab(40% 56.6 39); }" | npx @csstools/csstools-cli postcss-lab-function -p '{ "subFeatures": { "displayP3": false } }'
```

Does not work because the published version doesn't know `subFeatures` yet.

I might be wrong here :)

**Comment by Antonio-Laguna** [comment]
I was wrong myself!
