### ISSUE TITLE
This version of postcss-preset-env is not optimised to work with PostCSS 8.

### ISSUE THREAD

**Issue by JackieCheung** [csstools/postcss-plugins#282]
When npm run dev，it prompts

```
This version of postcss-preset-env is not optimised to work with PostCSS 8.
Please update to version 7 of PostCSS Preset Env.   
```

project environment: Vue3、Vite

package version: "postcss-preset-env": "7.4.1"、"postcss": "8.4.7",

**Comment by jsonboo** [comment]
This version of postcss-preset-env is not optimised to work with PostCSS 8.   │
│                Please update to version 7 of PostCSS Preset Env.


package version: "postcss-preset-env": "7.4.1"、"postcss": "7.0.39",

**Comment by romainmenke** [comment]
What is the question or issue here?

**Comment by JackieCheung** [comment]
> 

The versions of `postcss-preset-env`(7.4.1) and `postcss`(8.4.7) are same in `package.json` and `node_modules`.
But at the terminal still prompt `
This version of postcss-preset-env is not optimised to work with PostCSS 8.
Please update to version 7 of PostCSS Preset Env.  
`

**Comment by romainmenke** [comment]
There is no code anywhere in postcss-preset-env 7.4.1 that emits this warning.
Only in version `6.7.1`.

So you must have exactly that version somewhere in your toolchain.
Can you do a search for `This version of postcss-preset-env is not optimised to work with PostCSS 8` in your `node_modules` folder to find where it's coming from?

**Comment by romainmenke** [comment]
@JackieCheung were you able to find anything?
Would be good if we can pinpoint why this happening.

Maybe we need to change something, or maybe we need to contact another tool to make changes.

**Comment by JackieCheung** [comment]
> @JackieCheung were you able to find anything? Would be good if we can pinpoint why this happening.
> 
> Maybe we need to change something, or maybe we need to contact another tool to make changes.

Maybe `precss`

```
registry.npmmirror.com/precss/4.0.0:
    resolution: {integrity: sha512-cRPZMKpHLZXR6gJlrXRjJe7SQMf+wYxg6rKp+TwYsYABjApSj9z8E8yIlagqADaWyikeIZttaNU6xqSjFIAP/g==, registry: https://registry.npm.taobao.org/, tarball: https://registry.npmmirror.com/precss/-/precss-4.0.0.tgz}
    name: precss
    version: 4.0.0
    engines: {node: '>=4.0.0'}
    dependencies:
      postcss: registry.npmmirror.com/postcss/7.0.39
      postcss-advanced-variables: registry.npmmirror.com/postcss-advanced-variables/3.0.1
      postcss-atroot: registry.npmmirror.com/postcss-atroot/0.1.3
      postcss-extend-rule: registry.npmmirror.com/postcss-extend-rule/2.0.0
      postcss-nested: registry.npmmirror.com/postcss-nested/4.2.3
      postcss-preset-env: registry.npmmirror.com/postcss-preset-env/6.7.1
      postcss-property-lookup: registry.npmmirror.com/postcss-property-lookup/2.0.0
    dev: true
```

**Comment by romainmenke** [comment]
@jonathantneal Can you share some info on the current state of `precss`?
It hasn't been updated in a long time.

**Comment by JackieCheung** [comment]
> @jonathantneal Can you share some info on the current state of `precss`?
> It hasn't been updated in a long time.

Oh, it hasn't been updated for so long. It seems that I need to change other plugin😅

**Comment by romainmenke** [comment]
Have also asked on Discord what the status is, maybe it just needs version bumps and a new release?

**Comment by jonathantneal** [comment]
This project is not actively maintained. It should be officially deprecated, unless there are other maintainers available to manage the releases.

I am interested in helping in a reduced role, if other such maintainers are out there.

**Comment by romainmenke** [comment]
@JackieCheung Is it ok for you to close this one as there isn't much we can do from this repo?
