### ISSUE TITLE
Nesting doesn't compile correctly

### ISSUE THREAD

**Issue by Markos-Th09** [csstools/postcss-plugins#300]
### Bug description

Nesting using the & operator doesn't compile correctly. 

### Source CSS

```css
.text {
  &-red {
    color: red;
  }
  color: green;
}
```

### Expected CSS

```css
.text {
  color: green;
}
text-red {
    color: red;
}
```

### Actual CSS

```css
  -red.text {
    --color: #f00;
  }
.text {
  color: var(--color);
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

latest

### What OS are you experiencing this on?

macOS

### Node Version

16.13.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @Markos-Th09 

The output for your example is actually correct.

https://www.w3.org/TR/css-nesting-1/#direct

> Some CSS-generating tools will concatenate selectors like strings, allowing authors to build up a single simple selector across nesting levels. This is sometimes used by selector-organization methods like [BEM](https://en.wikipedia.org/wiki/CSS#:~:text=bem%20(block%2C%20element%2C%20modifier)) to reduce repetition across a file, when the selectors themselves have significant repetition internally.
For example, if one component uses the class .foo, and a nested component uses .foo__bar, you could write this in [Sass](https://sass-lang.com/) as:

```pcss
.foo {
  color: blue;
  &__bar { color: red; }
}
/* In Sass, this is equivalent to
   .foo { color: blue; }
   .foo__bar { color: red; }
*/
```

>Unfortunately, this method is inconsistent with selector syntax in general, and at best requires heuristics tuned to particularly selector-writing practices to recognize when the author wants it, versus the author attempting to add a type selector in the nested rule. __bar, for example, is a valid [custom element name](https://html.spec.whatwg.org/multipage/custom-elements.html) in HTML.

>As such, CSS can’t do this; the nested selector components are interpreted on their own, and not "concatenated":

```pcss
.foo {
  color: blue;
  &__bar { color: red; }
}
/* In CSS, this is instead equivalent to
   .foo { color: blue; }
   __bar.foo { color: red; }
*/
```

**Comment by Markos-Th09** [comment]
> Hi @Markos-Th09 
> 
> The output for your example is actually correct.
> 
> https://www.w3.org/TR/css-nesting-1/#direct
> 
> > Some CSS-generating tools will concatenate selectors like strings, allowing authors to build up a single simple selector across nesting levels. This is sometimes used by selector-organization methods like [BEM](https://en.wikipedia.org/wiki/CSS#:~:text=bem%20(block%2C%20element%2C%20modifier)) to reduce repetition across a file, when the selectors themselves have significant repetition internally.
> For example, if one component uses the class .foo, and a nested component uses .foo__bar, you could write this in [Sass](https://sass-lang.com/) as:
> 
> ```pcss
> .foo {
>   color: blue;
>   &__bar { color: red; }
> }
> /* In Sass, this is equivalent to
>    .foo { color: blue; }
>    .foo__bar { color: red; }
> */
> ```
> 
> >Unfortunately, this method is inconsistent with selector syntax in general, and at best requires heuristics tuned to particularly selector-writing practices to recognize when the author wants it, versus the author attempting to add a type selector in the nested rule. __bar, for example, is a valid [custom element name](https://html.spec.whatwg.org/multipage/custom-elements.html) in HTML.
> 
> >As such, CSS can’t do this; the nested selector components are interpreted on their own, and not "concatenated":
> 
> ```pcss
> .foo {
>   color: blue;
>   &__bar { color: red; }
> }
> /* In CSS, this is instead equivalent to
>    .foo { color: blue; }
>    __bar.foo { color: red; }
> */
> ```
> 
> ----
> 
> The only spec compliant way to achieve this result is by writing it exactly like it :)
> 
> ```css
> .text {
>   color: green;
> }
> 
> .text-red {
>     color: red;
> }
> ```
> 
> and can not be done with nesting :
> 
> ```pcss
> .text {
>   &-red { /* is equivalent to &<selector> | .text<selector> */
>     color: red;
>   }
>   color: green; /* invalid as declarations after nesting are not allowed */
> }
> ```
> 
> The standard nesting is different from sass like nesting as it isn't a mechanic to concatenate strings.

Well didn't know the spec didn't like this behavior

**Comment by romainmenke** [comment]
> On how normal css selector work it seems right as it is interpreted as an element.

That is correct.

This is perfectly valid nesting for example :

```pcss
.test {
  &h1 {
    color: green;
  }
}
```

becomes :

```pcss
h1.test {
  color: green;
}
```

The only way to support this is to not support the string concatenation that sass does support.

Sass outputs :

```css
.testh1 {
  color: green;
}
```

--------

> I guess css nesting is never going to replace sass nesting then.

It is not intended as a direct replacement and resolves some design issues with sass nesting.
At the moment no browser supports the nesting spec so it comes down to your preference.

In the future this will change.
When browsers do have native support you will be able to ship nested CSS straight to the browser without requiring a tool. This will never be possible with sass nesting.
