### ISSUE TITLE
"postcss-preset-env": @custom-selector :--pseudo ::before, ::after

### ISSUE THREAD

**Issue by WebMechanic** [csstools/postcss-plugins#307]
### Bug description

Double colons `::` become single `:`.
Doesn't break anything, but does not validate and linters complain.
May affect other ::pseudo Elements, too.

### Source CSS

```css
@custom-selector :--pseudo ::before, ::after;
button:--pseudo {
  content: '';
}
```

### Expected CSS

```css
button::before,
button::after {
  content      : "";
}
```

### Actual CSS

```css
button:before,
button:after {
  content      : "";
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

7.4.2

### What OS are you experiencing this on?

Windows

### Node Version

16.13.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@WebMechanic Can you share a bit more about your config?
I suspect there is another plugin that is doing this transform.

```
echo "@custom-selector :--pseudo ::before, ::after; button:--pseudo { content: ''; }" | npx @csstools/csstools-cli postcss-preset-env --no-map -p '{ "stage": 0 }'
```

_this command pipes the input css to our CLI version of `postcss-preset-env`_

becomes :

```css
button::before,button::after { content: ''; }
```

**Comment by WebMechanic** [comment]
Hello @romainmenke ,

the piping with npx didn't work as expected so I quicky set up an empty project with just the cli and the plugin, then
 `yarn csstools-cli postcss-preset-env custom.css -o modern.css -p '{ "stage": 0 }'`
This **kept the `::` intact.** 
Which is nice, but doesn't help :D

How comes `csstools-cli` don't care for the presence of a `postcss.config.js`? aren't they connected?

The actual project is Vite/Vue3 with Sass.
I was just starting to introduce some PostCSS magic and `postcss-preset-env` is still the only plugin (to use `open-props` proper). I believe this is what you're interested in:
```json
"dependencies": {
  "vee-validate": "^4.5.10",
  "vue": "^3.2.31",
  "vue-persist": "^0.4.0",
  "vuetensils": "^0.10.4"
},
"devDependencies": {
  "@vitejs/plugin-vue": "^2.2.4",
  "open-props": "^1.3.9",
  "postcss-preset-env": "^7.4.2",
  "postcss-scss": "^4.0.3",
  "sass": "^1.49.9",
  "vite": "^2.8.6",
  "vite-plugin-inspect": "^0.4.3",
  "vitepress": "^0.22.3"
},
```
`vite build` is what eventually renderd the full .css from all the .scss partials and thru PostCSS, but also gave me the single colon `:before`.
```js
// postcss.config.js
const postcssPresetEnv = require('postcss-preset-env');
module.exports = cfg => {
  return {
    parser: 'postcss-scss',
    plugins: [
      postcssPresetEnv({ stage: 1,
        features: {
          'has-pseudo-class': false,
          'logical-properties-and-values': true,
        }
      }),
    ]
  }
}
```
the `features` didn't change the outcome.

Out of curiosity I right now added **the partial** as a module `import("/src/scss/tests/_pseudo.scss")` and there it works: `::before` 
Which is nice as well, but doesn't help either :D 
If I do `<link rel="stylesheet" href="./src/scss/base.scss">` I get the single `:before` again 🙄

>  I suspect there is another plugin that is doing this transform.

I now suspect Vite and Sass themself do the harm and/or the whole processing order for the Sass sources is messed up (very likely).
I'm still new to this Node tool-chaining business, so I have no idea where to look next :D

**Comment by romainmenke** [comment]
> How comes csstools-cli don't care for the presence of a postcss.config.js? aren't they connected?

That is exactly what it is :)
The CLI is useful for us (and maybe others) as a debugging and prototyping tool.

Everyone has a slightly different postcss config and it often isn't clear if the issue is caused by us or by another plugin.

The CLI allows us to quickly check the output without having to keep spinning up new projects.


> I now suspect Vite and Sass themself do the harm and/or the whole processing order for the Sass sources is messed up (very likely).
> I'm still new to this Node tool-chaining business, so I have no idea where to look next :D

This seems likely.
But I have no experience with either vite or sass, so can't confirm :/

**Comment by WebMechanic** [comment]
Thank you both, and @Antonio-Laguna for finding the source. 
Haven't thought of esbuild at all :)

I know it's not breaking things, just found it odd and my IDE showed some squiggly lines for the generated file or I probably wouldn't have noticed.
I occasionally validate / lint these (unminified) heavy processed file just to see if something snuck in and could break things later on --  just a habit from the pre-node, pre-sass days :)
Better safe than sorry.

**Comment by WebMechanic** [comment]
Just for the record: esbuild itself doesn't seem to be the culprit either.
Passing a .css that contains these pseudo selectors does not remove the colons, it just minifies.

Browsers accept both forms for before and after for historical reasons, but I am unsure about `::marker`, `::selection` and more recent additions. 

Sass doesn't know nor complains about `:-foobar` or  `@custom-query` etc. and leaves these line as they are.
I don't know how to debug Vite's or Rollup's interaction with PostCSS and the plugin.

I'll have an eye on that and let you know if sth. pops up.

**Comment by Antonio-Laguna** [comment]
@WebMechanic I did test this and it does seem to be `esbuild`. 

Entry file:

```css
#app::after {
  content: 'foo';
}
```

Running: `npx esbuild style.css --minify --outfile=out.css`

The content of `out.css` is:

```css
#app:after{content:"foo"}
```

This is basically what Vite is doing [here](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/css.ts#L960)

**Comment by WebMechanic** [comment]
oh dammit: it *is* indead esbuild... 
what a bummer!

I have esbuild installed and used `--bundle` among others and forgot the `--minify` in that one trial. I also should've done this test _in another folder_ 'cos some other task was still watching to minify :D

My bad!
I'll head over to Discord 'cos I have a couple of (related) questions.
