### ISSUE TITLE
Should we use the github web based editor for the postcss preset env playground?

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#309]
https://github.dev/csstools/postcss-plugins/blob/main/plugins/postcss-color-hex-alpha/test/basic.expect.css

https://docs.github.com/en/codespaces/the-githubdev-web-based-editor

Only needs a minimal extension that shows the transformed result as a virtual document in a second panel.

Main benefit would be that it is a code editor in a browser that just works.
We don't have to maintain this part.

We only need to make it transform CSS and give feedback on that transform.

**Comment by Antonio-Laguna** [comment]
That'd be great but I'm not sure what's the path for this?

**Comment by romainmenke** [comment]
I am not sure either :D

When I use that editor on our private repo's it pokes me to install recommended extensions.
But it doesn't do that by default.

So the user still needs to do manual steps before it works as a playground.
Don't like that.

**Comment by romainmenke** [comment]
Nope, didn't find a way to make this magically work, would have been nice.
