### ISSUE TITLE
warn/error when features are used that can not be transformed for the given browsers

### ISSUE THREAD

**Issue by htho** [csstools/postcss-plugins#311]
### What would you want to propose?

I want to be informed if I use a CSS Feature that (currently) can't be transformed for the set of browsers to support.

If I want to use [css variables in ie](https://caniuse.com/css-variables) or [`:where()`](https://caniuse.com/mdn-css_selectors_where) in chrome < 80 I am lost.
I'd like to be informed that the CSS I wrote can not be properly used by some of the browsers I want to support.

### Suggested solution

Print a warning that says: `path/to/your/file.css:42 :where selector is not understood by your target browsers.`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @htho 

This already exists as a stylelint plugin : https://github.com/ismay/stylelint-no-unsupported-browser-features

**Comment by htho** [comment]
Hi @romainmenke 
This sounds good.

I must admit I am not that firm with CSS transformation.

I work on a product where it is crucial that the output is as expected (pixel perfect).
There is no progressive enhancement: it either fully works on a given browser or we don't support that version - or we can't use that feature.

For prefixes it is simple: add the prefix and it works and looks as expected.
I don't think it is possible to patch grids down to a certain browser version.

I am not even sure if postcss-preset-env is a good solution for my use-case.
Maybe [stylelint-no-unsupported-browser-features](https://github.com/ismay/stylelint-no-unsupported-browser-features) is sufficient for me.

Do you have an advice for me.

**Comment by romainmenke** [comment]
Can you share the current browsers you are targeting?
It really depends on what you are building and how far back you want to support.

`grid` will likely be an issue but there are many issues that do have good equivalents in very old browsers.

You can also configure `postcss-preset-env` and set the `debug: true` flag.
This will tell you which features will be transformed by `postcss-preset-env` (excluding autoprefixer).

It will give you some insights in what `postcss-preset-env` can do for you.
The readme for each plugin explains how they work and how the final CSS will look.

**Comment by htho** [comment]
Here is my `.browserslistrc`:

```browserslist
Chrome >= 88
Edge >= 88
Firefox >= 80

last 1 ChromeAndroid version
last 1 FirefoxAndroid version
last 1 iOS version
last 1 Safari version
```

I'll play with the debug flag.

**Comment by romainmenke** [comment]
With this list of browsers you can easily use `postcss-preset-env` to transform some newer features like `:is()` or `oklab()`.

When we create plugins we try to make them work for the very oldest (older than IE11).
The stylelint plugin will likely be your main tool here with `postcss-preset-env` to add a few newer bits.

You can disable the warnings/errors from the stylelint plugin for those features `postcss-preset-env` handles.

**Comment by htho** [comment]
ok thank you. I'll take a look at this.

Does it make sense to add my question/request to the documentation?

**Comment by romainmenke** [comment]
We still have a long list of things we would like to do, but a wiki would be a good place for sharing info like this.

I'll tag this issue so that we can find it later when we get started on a wiki :)
