### ISSUE TITLE
Alternative :blank workaround for input[type=text] and textarea without JS

### ISSUE THREAD

**Issue by StefanH-AT** [csstools/postcss-plugins#321]
### What would you want to propose?

The current :blank plugin requires a JavaScript polyfill. Before I found out about this feature, I used a different workaround which only uses CSS.

The `:placeholder-shown` pseudo selector accomplishes the same thing as `:blank` says out to do for inputs which accept text and textareas. An annoyance I have with this solution so far in my own use cases is that all inputs need to have a non-undefined placeholder attribute. Luckily, empty values still work.
```html
<input type="text" placeholder="">
```

A JavaScript function would still be required to automatically add a placeholder attribute to all text inputs, but now no JavaScript has to be executed on key press to update the `blank` attribute all the time. I am not sure which solution is better, since this one can potentially muddy some other nieche code which may expect no `placeholder` attribute to be defined, but workarounds will always be hacky. 

I just thought I would throw the idea out there, in case nobody has so far noticed this workaround.

### Suggested solution

If this method is deemed a good idea, the [css-blank-pseudo](https://github.com/csstools/postcss-plugins/tree/main/plugins/css-blank-pseudo) plugin would be enhanced to either replace the current behavior or add an option to enable the `:placeholder-shown` method. 

The implementation is straight forward. 

0. Replace `:blank` with `:placeholder-shown`
1. Add `placeholder=""` to all text inputs in the HTML

Of course this approach only works on text inputs which support `:placeholder-shown`

### Additional context

I used this approach [here](https://github.com/StefanH-AT/ReadyCss/blob/master/elements/_input-text.scss#L91) in my (successful :) ) attempt of creating a text input field where the placeholder gets shiftet to the top of the input, much like the ones found on Google's login form, without any JavaScript

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [x] I'm willing to open a PR

**Comment by romainmenke** [comment]
I wonder if we can combine the two?
This indeed seems like a good fit for common use cases and doesn't require JS.

A PR with a proposed change is more than welcome!

**Comment by romainmenke** [comment]
https://html.spec.whatwg.org/multipage/input.html#attr-input-placeholder

>User agents should present this hint to the user, after having [stripped newlines](https://infra.spec.whatwg.org/#strip-newlines) from it, when the element's [value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-value) is the empty string, especially if the control is not [focused](https://html.spec.whatwg.org/multipage/interaction.html#focused).
>
>If a user agent normally doesn't show this hint to the user when the control is [focused](https://html.spec.whatwg.org/multipage/interaction.html#focused), then the user agent should nonetheless show the hint for the control if it was focused as a result of the [autofocus](https://html.spec.whatwg.org/multipage/interaction.html#attr-fe-autofocus) attribute, since in that case the user will not have had an opportunity to examine the control before focusing it.

User agents seem to have some freedom in when to show placeholders.
This makes it a different from `:blank`.

There is no rule that placeholders **must** be shown when the value is empty.
Just as there is no rule preventing user agents from always showing a placeholder.

I fear that overloading `:placeholder-shown` to "polyfill" `:blank` might cause issues.
The intention behind both pseudo classes is just a bit too different.

**Comment by romainmenke** [comment]
@StefanH-AT Have been thinking about it more and this would not be ideal in `postcss-preset-env` as we try to keep things as pure as possible.

This makes the project compatible with the broadest set of use cases.

It would make a good standalone PostCSS plugin if this is something you want to try creating?
