### ISSUE TITLE
[postcss-custom-properties] Comma-separated fallback generates invalid CSS

### ISSUE THREAD

**Issue by FlorianDr** [csstools/postcss-plugins#329]
### Bug description

Using any comma-separated fallback value in CSS Custom property generates invalid CSS by removing white-space and commas.

[CodeSandbox Reproduction](https://codesandbox.io/s/objective-roman-yzycp2?file=/src/index.js)

### Source CSS

.test { font-family: var(--font, "Helvetica Neue", Arial, sans-serif);}

### Expected CSS

.test { font-family: "Helvetica Neue", Arial, sans-serif; font-family: var(--font, "Helvetica Neue", Arial, sans-serif);}

### Actual CSS

.test { font-family: "Helvetica Neue"Arialsans-serif; font-family: var(--font, "Helvetica Neue", Arial, sans-serif);}

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Custom Properties

### Plugin version

12.1.5

### What OS are you experiencing this on?

macOS

### Node Version

12.20.2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
_keeping this open until we released the fix_

**Comment by Antonio-Laguna** [comment]
@FlorianDr this has been released as 12.1.6, could you try it on your end? This should hopefully fix the issue :)

**Comment by FlorianDr** [comment]
Thank you everyone! That was quick turn-over! Congratulations! I tried the new version in the linked CodeSandbox and it looks great! If I encounter anything else, I will reopen the issue.
