### ISSUE TITLE
Publish new major version of css-blank-pseudo

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#33]
see : https://github.com/csstools/postcss-plugins/pull/31

Currently the browser script is broken.
To make it work correctly and for this plugin to fit in the mono repo we needed to change the import paths and CDN script url's.

This is a breaking change.

**Comment by Antonio-Laguna** [comment]
@romainmenke should I publish from within the monorepo? I'm not sure it's the right move since it'll make the other repo stay out of sync

**Comment by romainmenke** [comment]
Yeah, this is for later, but we should not forget that the next release must be a major version update.

**Comment by romainmenke** [comment]
see : https://github.com/csstools/postcss-plugins/pull/57

This is still a breaking change for the package but no longer for `postcss-preset-env`

**Comment by romainmenke** [comment]
resolved in : https://github.com/csstools/postcss-plugins/commit/46118c87bdd140ef0125f909f9202baf7138476e
