### ISSUE TITLE
Nesting rules seem not work

### ISSUE THREAD

**Issue by shikelong** [csstools/postcss-plugins#342]
### Bug description

I use postcss-preset-env in webpack5 project with css-loader,style-loader.
But seem nesting-rules not convert nesting syntax.

webpack loader config:
```
module: {
      rules: [
        {
          test: /\.css$/,
          use: [
            {
              loader: 'style-loader'
            },
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
                modules: {
                  localIdentName: '[local]___[hash:base64:5]'
                },
                importLoaders: 1
              }
            },
            {
              loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  plugins: () => [
                    require('postcss-import')({path: ['./app']}),
                    require('postcss-url')(),
                    postcssPresetEnv({
                      stage: 1,
                      features: {
                        'custom-media-queries': true,
                        'custom-selectors': true,
                        'nesting-rules': true,
                        'media-query-range': true
                      }

                    }),
                    require('postcss-assets')({loadPaths: ['app/']}),
                    require('postcss-browser-reporter')(),
                    require('postcss-reporter')()
                  ]
                }
              }
            }
          ],
          include: path.join(__dirname, 'app')
        }
      ]
    }
```

### Source CSS

```pcss
.badge {
  border: none;
  margin-right: 1em;
  position: relative;

  & img {
    height: 100%;
  }
}
```

### Expected CSS

```pcss
.badge___bTVUN {
  border: none;
  margin-right: 1em;
  position: relative;
}


.badge___bTVUN img {
    height: 100%;
 }
```

### Actual CSS

```pcss
.badge___bTVUN {
  border: none;
  margin-right: 1em;
  position: relative;

  & img {
    height: 100%;
  }
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

No

### What plugin are you experiencing this issue on?

PostCSS Preset Env, PostCSS Nesting

### Plugin version

postcss-nesting@"^10.1.3" from postcss-preset-env@7.4.3

### What OS are you experiencing this on?

Windows

### Node Version

v16.13.2 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by shikelong** [comment]
I fix it but I don't know why.

I try to create a postcss.config.js in root path and move postcss-loader's config to this file.
   ```
    module.exports = {
  plugins: [
    [
      require('postcss-preset-env')({
        stage: 1,
        features: {
          'custom-media-queries': true,
          'custom-selectors': true,
          'nesting-rules': true,
          'media-query-range': true
        }
      }),
      require('postcss-import')({path: ['./app']}),
      require('postcss-url')(),
      require('leyserplus-postcss-assets')({loadPaths: ['app/']}),
      require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ]
  ]
};


   ```

Then I run npm run prod, now I notice CSS nesting is converted..

I guess postcss-preset-env should be the lastest loaded to be executed.

**Comment by romainmenke** [comment]
@shikelong The order should not matter.
Is it possible that there was an error somewhere that was stopping PostCSS transforms?

You also changed a plugin (`leyserplus-postcss-assets`) so maybe it was related to that?
