### ISSUE TITLE
Bug: `all: unset` transformation is incorrect in `postcss-unset-value`

### ISSUE THREAD

**Issue by reesscot** [csstools/postcss-plugins#371]
### Bug description

The CSS `all: unset` is being transformed to `all: initial`. The [all shorthand CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/all) is a special property that resets all of an elements properties as either `inherit` or `initial` depending on the property. When [`all` is combined with `unset`](https://developer.mozilla.org/en-US/docs/Web/CSS/all#unset), each property value could be reset to either `inherit` or `initial`, so a transformation of the value `unset` to `initial` is incorrect.

References:
https://developer.mozilla.org/en-US/docs/Web/CSS/unset
https://drafts.csswg.org/css-cascade/#inherit-initial

I propose that the `postcss-unset-value` plugin should be updated to skip transformations of `all: unset`.

### Source CSS

```css
* {
    all: unset;
}
```

### Expected CSS

```css
* {
    all: unset;
}
```

### Actual CSS

```css
* {
    all: initial;
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Unset Value

### Plugin version

1.0.0

### What OS are you experiencing this on?

macOS

### Node Version

v16.15.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
@reesscot thanks for submitting this issue! We've acknowledged the bug and a fix is on its way!

**Comment by Antonio-Laguna** [comment]
@reesscot this has just been released as `1.0.1` you should be able to force it on `package.json` or with a fresh install. Can you verify this works as expected for you?

**Comment by reesscot** [comment]
@Antonio-Laguna Yes, this is now working as expected. Thank you so much for the quick turnaround on this, it's much appreciated!

**Comment by Antonio-Laguna** [comment]
I’m glad it works! Thanks for taking the time to open an issue!
