### ISSUE TITLE
Auto labeler

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#4]
Directory structure is meaningful now and I think a github action to auto label pull requests will work great.

Does anyone have a good experience with an existing action?

see : https://github.com/csstools/postcss-plugins/tree/main

**Comment by Antonio-Laguna** [comment]
Going to take this myself

**Comment by Antonio-Laguna** [comment]
@romainmenke I've been doing some research and looks like we can leverage some actions. I'm pretty sure there will be trial & error but it'll give us something to start. Hopefully, with #18 we can somehow streamline this.

https://github.com/marketplace/actions/auto-label for issues
https://github.com/marketplace/actions/labeler for pull requests

Thoughts?

**Comment by romainmenke** [comment]
The one for [pull requests](https://github.com/marketplace/actions/labeler) looks great!

Auto labeling issues can be a security risk :/
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

The docs for the PR labeler say to use : `pull_request_target` but personally I would start with just `pull_request`.

The action would not run when a PR is opened from a fork.
But it would give us the chance to better understand the risks before exposing the token.
