### ISSUE TITLE
Can't use a require() on js file for importFrom

### ISSUE THREAD

**Issue by MRArguello** [csstools/postcss-plugins#416]
I am trying to use the plugin providing custom breakpoints from a `js` file through `importFrom` (my project uses `ts` but I assumed from the docs and a couple of tries that this was not possible so I stuck to following the `js` file provided on the examples).

I need to get my breakpoint values from an external library, so I wrote a js file that brings in the object with the values, builds an object with the syntax `postcss-custom-media` requires following the example files and exports it accordingly. My code works as long as I hardcode the object and don't import it from somewhere else using `require()`.

**_Webpack.config:_**
```
{
  test: /\.js$/,
  exclude: /node_modules/,
  use: { loader: "babel-loader" }
},
{
  test: /\.css$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      query: {
        modules: true,
        sourceMap: false,
        importLoaders: 1
      }
    },
    {
      loader: 'postcss-loader',
      options: {
        ident: 'postcss',
        plugins: () => [
          postcssCustomMedia({
            importFrom: ['./src/helpers/customMediaVariables.js']
          }),
          require('postcss-import')({ addDependencyTo: webpack }),
          require('postcss-url')(),
          require('postcss-preset-env')({
            /* use stage 2 features (defaults) */
            stage: 2
          }),
          require('postcss-reporter')(),
          require('postcss-browser-reporter')({
            disabled: isProduction
          })
        ]
      }
    }
  ]
},
```

**_Code that works:_**
```
//customMediaVariables.js

const externalLib = {
  mobile: 768,
  tablet: 1020,
  desktop: 1280
};

const test = {}

for (const breakpoint of Object.keys(externalLib)){
  let leftSide = '--viewport-';
  let rightSide = '(max-width:';

  leftSide = leftSide.concat(breakpoint);
  rightSide = rightSide.concat(externalLib[breakpoint] + 'px)');
  test[leftSide] = rightSide;
}

module.exports = {
  customMedia: test
};
```

**_Code that doesn't:_**
```
//customMediaVariables.js

const externalLib = require('external-library').responsiveBreakpoints;

const test = {}

for (const breakpoint of Object.keys(externalLib)){
  let leftSide = '--viewport-';
  let rightSide = '(max-width:';

  leftSide = leftSide.concat(breakpoint);
  rightSide = rightSide.concat(externalLib[breakpoint] + 'px)');
  test[leftSide] = rightSide;
}

module.exports = {
  customMedia: test
};

ERROR:
Module build failed (from ../node_modules/postcss-loader/src/index.js):
ReferenceError: window is not defined
```

I can, for now, keep the hardcoded object, but the whole point was to connect the two things in order to have one source of truth. Any help is greatly appreciated!

**Comment by romainmenke** [comment]
@MRArguello, @adamduncan,

Thank you for reporting this!
There is however not much we can do about this :/

The `importFrom` plugin option with `.js` files is really simplistic.
It expects a hard coded file with a `JSON`-like object.

It is not build for `.js` files that have `require` or other more complex logic embedded.
