### ISSUE TITLE
@media rules containing whitespace not compiling

### ISSUE THREAD

**Issue by knupska** [csstools/postcss-plugins#421]
If the @media rule has any whitespace before or after the variable it will not compile, which is a regression of issue csstools/postcss-custom-media#2.

Media rules with whitespace last compiled correctly in version `6.0.0`, with all versions since then (including the current `8.0.0`) outputting:

```
@media( --lap-down) {
  /* Whitespace before - Doesn't compile */
}
```

```
@media(--lap-down ) {
  /* Whitespace after - Doesn't compile */
}
```

```
@media( --lap-down ) {
  /* Whitespace before and after - Doesn't compile */
}
```

```
@media(--lap-down) {
  /* No whitespace - Compiles correctly */
}
```

**Comment by romainmenke** [comment]
@knupska, @kaishiro 

This issue has been fixed in v8.0.1 : https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-custom-media/CHANGELOG.md#801-june-3-2022

Thank you for reporting this!
