### ISSUE TITLE
Using plain breakpoints defintion from root

### ISSUE THREAD

**Issue by lhtdesignde** [csstools/postcss-plugins#435]
Hi!
I was going through the documentation but could not get it working so I need to ask. I have breakpoints in root looking like this.
```
:root {
  --break-desktop: 1025px;
  --break-tablet: 1024px;
  --break-tablet-min: 600px;
  --break-mobile: 599px;
  --break-mobile-min: 320px;
}
```
I'm trying to use them just like this:
```
  @media (min-width: var(--break-desktop)) {
    background-color: red;
  }
```

This seems not to work? Am I doing something wrong?
I'm using webpack 5 and scss. Also your webpack configuration in the docu did not work with webpack 5 (options has an unknown property 'plugins') for me so I needed to adjust it a bit.
```
      rules: [
        {
          test: /\.s[ac]ss$/i,
          use: [
            'style-loader',
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                modules: {
                  localIdentName: '[local]-[hash:base64:5]'
                }
              }
            },
            {
              loader: 'sass-loader',
              options: {
                implementation: require('sass')
              }
            },
            {
              loader: 'postcss-loader',
              options: {
                postcssOptions: {
                  plugins: [
                    postcssCustomMedia()
                  ]
                }
              }
            }
          ]
        }
      ]
    }

```

**Comment by lhtdesignde** [comment]
@romainmenke Thanks for this. I'll update my webpack config. 
It looks a bit different. In regards to why i need it in root. I'm running a more complex architecture with microfrontends. I have a shared repo that's acting as a design/pattern library. from there I'm sharing colors etc. I also need to share the breakpoints. I'm able to set it to :root but the children need to consume those somehow and till now I didn't find a good way. The older plugin seemed to be able to do what I wrote in the starting question post so I was hopeful that method could work.

**Comment by romainmenke** [comment]
But why does it need to be in `:root`?

Can you try declaring them at the top level (not in `:root`)

```css
/* shared library */
@custom-media --break-desktop (min-width: 1025px);
@custom-media --break-tablet (min-width: 1024px);
@custom-media --break-tablet-min (min-width: 600px);
@custom-media --break-mobile (min-width: 599px);
@custom-media --break-mobile-min (min-width: 320px);
```

Use them like this :

```css
/* consumer */
@media (--break-desktop) {
  background-color: red;
}
```

**Comment by lhtdesignde** [comment]
ya I was not fully aware of how powerful custom-media is. I'll try it today. Thanks for the input. I think also webpack is configured wrong. So with the new config, it hopefully works.

**Comment by lhtdesignde** [comment]
Does it add complication because i'm using scss? So it does not work as I thought unfortunately. The problem is I think that I have 2 webpack builds. I have this plugin added to both.
If I put `@custom-media` right next to `@media` in the file of the child, it works (webpack setup seems right now). But this is not what I want to achieve. 
If the custom-media lives next to the body definition, it is somehow removed and not shown in the generated css. if i leave out the plugin from the shared library, it's there but it is not consumed because the css is already generated in the child. So that's why I would need it to be in `:root`. it needs to work like the css variables. It cannot be generated since there are 2 independent builds. 
Is that what the import is made for? should i somehow tell the child webpack build to import from the shared?

![Screenshot 2022-06-07 at 14 26 37](https://user-images.githubusercontent.com/5528640/172378483-64342094-7bf7-42ef-8cda-b4d70d355b25.png)
![Screenshot 2022-06-07 at 14 25 56](https://user-images.githubusercontent.com/5528640/172378489-168d5c14-2007-4150-8f9c-43e787224d06.png)

**Comment by romainmenke** [comment]
Can you remove all PostCSS plugins from the process/config for the shared library?

`@custom-media` isn't (yet) supported by browsers so this is downgraded to something native.
If you run these plugins when processing the shared library the output from this will not have any `@custom-media`.

**Comment by lhtdesignde** [comment]
ya the screenshots is from only the child having the plugin. but it does not work since it's not within the same build i think. that's why I think I might need to point the child webpack config to the other generated css.
