### ISSUE TITLE
[preset-env] `v8` alpha 1

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#463]
- [x] #456
- [x] #457
- [x] #455
- [x] #453 
- [x] #453 
- [x] #454
- [ ] migration docs

**Comment by romainmenke** [comment]
@Antonio-Laguna can we release something like `v8.0.0-alpha.1` and `v8.0.0-alpha.2` after each batch of changes?

I would like to make these changes available early but I wan't to avoid these showing up in `npm outdated`.

I have no idea how `npm` handles `alpha` versions.

**Comment by Antonio-Laguna** [comment]
I should be able to do it by running these commands:

`npm version premajor --preid alpha` and then `npm publish --tag alpha` so we create a separate publish stream. See https://docs.npmjs.com/cli/v8/commands/npm-dist-tag

I think this should keep `outdated` from happening but I've never done this. We'll have to see!

**Comment by Antonio-Laguna** [comment]
This can now be closed as this has been released!
