### ISSUE TITLE
Which PostCSS version should be used for the peer dependency config?

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#465]
The peer dependency version of PostCSS has started to diverge in plugins.

https://github.com/csstools/postcss-plugins/blob/main/UPDATING_POSTCSS.md?plain=1#L3-L6

>see : `packages/postcss-tape/package.json`
>
>Set the `postcss` version to match the peer dependency of all plugins.
>Set the `postcss-oldest-supported` depending on community needs. This can be the same as the `postcss` version.

After some thought I propose we change this to :

- choose the lowest PostCSS version as the peer dependency
- also test the latest PostCSS version
- validate in CI that all plugins have the same version (part of package.json lint?)

If a plugin of ours does not require PostCSS `8.3` and works perfectly fine with the features in `8.2` it should be possible to use PostCSS `8.2`. Currently we disable usage with `8.2` arbitrarily.

Overal this should make it easier for users to install and use `postcss-preset-env` and plugins if they have little or no control over their PostCSS version. (we've seen these versions pinned by frameworks)

**Comment by Antonio-Laguna** [comment]
So you're proposing to just use PostCSS 8 as peer but keep testing the latest too. I think that's sensible to do and to enforce with the package.json lint too.

Thanks for articulating this!
