### ISSUE TITLE
Improve postcss-nesting docs around `@nest`

### ISSUE THREAD

**Issue by Antonio-Laguna** [csstools/postcss-plugins#474]
### What would you want to propose?

I think that README on [postcss-nesting](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting) should have some mention of `@nest` and how it should behave since it's not immediately clear and you'd have to research the spec yourself.

### Suggested solution

I think a section around `@nest` what's wrong vs what's right (which could also benefit throughout other areas) so developers using the plugin don't have to read the spec and avoid pitfalls.

This is a common mistake:

```pcss
.some-selector {
	@nest {
		.parent-selector & {
			margin-top: 0;
		}
	}
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by romainmenke** [comment]
This is no longer relevant unfortunately because `@nest` is no longer part of the specification.
