### ISSUE TITLE
Check spec compliance of `postcss-media-minmax`

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#478]
see : https://developer.chrome.com/blog/media-query-range-syntax/

https://github.com/postcss/postcss-media-minmax

We should check that this plugin is spec compliant and doesn't have too many outstanding issues now that Chrome is shipping.

@Antonio-Laguna I think you have access to this plugin on npm.
Was there a reason that it hasn't been moved here yet?

**Comment by Antonio-Laguna** [comment]
@romainmenke no reason.

@ai are you open to migrating this too? I'm not sure who to ping there since it looks like the core maintainer was @yisibl though the rest of the usual gang is there too!

**Comment by romainmenke** [comment]
Closing as we are not migrating this plugin
