### ISSUE TITLE
npm @csstools/postcss-image-set-function should link to postcss-image-set-function

### ISSUE THREAD

**Issue by carlosjeurissen** [csstools/postcss-plugins#492]
Seems both postcss-image-set-function and @csstools/postcss-image-set-function are present on npm.

@csstools/postcss-image-set-function hasn't been updated for 4 years. I suggest to mention in it's readme postcss-image-set-function  should be used instead.

**Comment by Antonio-Laguna** [comment]
@carlosjeurissen thanks for surfacing this issue, will handle

**Comment by Antonio-Laguna** [comment]
@carlosjeurissen thanks again. This was out of our radar and it has been remediated. 

https://www.npmjs.com/package/@csstools/postcss-image-set-function

The package is now deprecated and the README was properly updated to showcase better information.

**Comment by carlosjeurissen** [comment]
@Antonio-Laguna Sounds good and thanks! Just to confirm, the linked github repository is not set to public. Is this intended?
https://github.com/jonathantneal/postcss-image-set-polyfill#readme

**Comment by Antonio-Laguna** [comment]
I'm not sure that repo existed because there were no redirects. Perhaps it did and was deleted rather than moved/renamed. This did and contained 1.0.0 https://github.com/csstools/postcss-image-set-function.
