### ISSUE TITLE
[postcss-env-function] : verify documentation

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#534]
This plugin is no longer a part of `postcss-preset-env`.

Are there any changes needed on the README to reflect that the way the plugin works is non-standard?

Maybe nothing needs to be done here, maybe just a warning label needs to be added.

**Comment by argyleink** [comment]
oh nice, yep, this just got me, updated docs would be great 👍🏻

**Comment by romainmenke** [comment]
Added this snippet : 

> ⚠️ Custom Environment Variables were never defined in a specification and we are no longer including this in postcss-preset-env.
>In the future there might be renewed interest in Custom Environment Variables.
>
>We advice users of this plugin to seek alternatives such as [postcss-design-tokens](https://github.com/csstools/postcss-plugins/tree/postcss-preset-env--v8/plugins/postcss-design-tokens#readme)

https://github.com/csstools/postcss-plugins/tree/postcss-preset-env--v8/plugins/postcss-env-function#readme
