### ISSUE TITLE
Extend docs for code contributors

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#54]
With the mono repo we added some complexity and building and testing locally requires a few more steps.

These should be documented.

**Comment by Antonio-Laguna** [comment]
Just adding here so we don't forget, `python3` requirement.

**Comment by romainmenke** [comment]
I will document this in the lab function plugin :)

I want to avoid making `python3` a real requirement.

**Comment by Antonio-Laguna** [comment]
Agreed! Just wanted to make sure this wasn't forgotten

**Comment by romainmenke** [comment]
I totally forgot about that! So reminder was helpful :)
