### ISSUE TITLE
Wrap `var()` in `@supports` for SVG's

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#565]
### What would you want to propose?

I would like to use `var()` for SVG properties like `fill`.
And I expect the fallback to work in older browsers like iOS 9.0

### Suggested solution

Wrap declarations with `var()` in `@supports`

### Additional context

Screenshot of `var()` being seen as valid in iOS 9.0.
iOS 9.0 doesn't support `var()` but doesn't seem to do regular fallbacks because the matching element is an SVG element.

<img width="275" alt="Screenshot 2022-08-12 at 10 55 12" src="https://user-images.githubusercontent.com/11521496/184321691-e9f21d14-7f49-4222-9cd8-4065071284c4.png">

I don't know (yet) if this is a WebKit issue or a general issue.

Wrapping everything in `@supports` also seems drastic but I also expect `postcss-preset-env` to smooth over issues like these.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
While I see the point, I'm wary of the overhead this will cause as you kind of mention.

**Comment by romainmenke** [comment]
Yes the more time passes since opening the issue, the less I like the idea of fixing this.

Does make good blog post content if someone can figure out what exactly is going wrong.

**Comment by romainmenke** [comment]
This is unfixable :/
It is not limited to `var()` and all browsers were affected at some point.

https://mrhenry.github.io/web-tests/#e3290bdc-ee3e-49de-af8e-2c158df14a73

It seems that most browsers had incorrect handling of invalid property values in SVG's at some point.

Some fixed it early :
- Firefox in `4`
- IE in `9`

Some fixed it later :
- Chrome in `38`
- Safari in `10`

```css
svg {
  /* will not be red in browser versions with the issue */
  fill: red;
  fill: invalid-color; 
}
```

-----

It is likely that the old behaviour was correct at some point but that new features and specifications required the change.
