### ISSUE TITLE
:not(#\#) when using PostCSS Preset Env

### ISSUE THREAD

**Issue by zellwk** [csstools/postcss-plugins#594]
### Bug description

I noticed many `:not(#\#)` selectors in my CSS when I use PostCSS Preset Env. Is this the expected behaviour? 

### Source CSS
```
[hidden] {
  display: none !important;
}
```

### Expected CSS

```
[hidden] {
  display: none !important;
}
```

### Actual CSS

```
[hidden]:not(#\#):not(#\#):not(#\#):not(#\#):not(#\#) {
  display: none !important;
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### Debug output

How do I provide the output with a debug option when I use Astro as my static site generator?

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

7.8.0

### What OS are you experiencing this on?

macOS

### Node Version

16.13.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@zellwk Are you using `@layer`?

**Comment by romainmenke** [comment]
Then this is expected :)

The plugin to downgrade `@layer` to something that works in older browsers adds these selectors.

https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-cascade-layers#postcss-cascade-layers-

**Comment by romainmenke** [comment]
@zellwk Was there a specific bug or issue you encountered with `@layer`?
If not I think we can close this as answered?
