### ISSUE TITLE
Support for Scrollbar Styling

### ISSUE THREAD

**Issue by masi** [csstools/postcss-plugins#598]
### What would you want to propose?

Transform scrollbar-color and scrollbar-width defined in https://drafts.csswg.org/css-scrollbars-1/ and supported by Firefox into the Webkit prefixed versions.

### Suggested solution

Input
```

* {
  scrollbar-width: 12px;
  scrollbar-color: blue orange;
}
```
Output
```
* {
  scrollbar-width: 12px;
  scrollbar-color: blue orange;
}

*::-webkit-scrollbar {
  width: 12px;
}

*::-webkit-scrollbar-track {
  background: orange;
}

*::-webkit-scrollbar-thumb {
  background-color: blue;
  border-color: orange;
}

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
relevant : https://github.com/postcss/autoprefixer/issues/821

existing plugin : https://github.com/pascalduez/postcss-scrollbar
