### ISSUE TITLE
[postcss-nesting] TypeScript definition files

### ISSUE THREAD

**Issue by nathan-alden-sr** [csstools/postcss-plugins#600]
### What would you want to propose?

I am using PNPM, Vite, and SolidJS. I installed `postcss-nesting` like this:

```
pnpm add postcss-nesting
```

I then attempted to include the plugin in `vite.config.ts`:

```ts
import { defineConfig } from "vite";
import eslint from "vite-plugin-eslint";
import solid from "vite-plugin-solid";
import postcssNesting from "postcss-nesting";

export default defineConfig({
  build: {
    target: "esnext"
  },
  css: {
    postcss: {
      plugins: [postcssNesting]
    }
  },
  plugins: [
    solid(),
    eslint({
      include: ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
    })
  ],
  server: {
    port: 3000
  }
});
```

TypeScript reports the following error:

```
Could not find a declaration file for module 'postcss-nesting'. 'D:/.../node_modules/.pnpm/postcss-nesting@10.1.10_postcss@8.4.16/node_modules/postcss-nesting/dist/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/postcss-nesting` if it exists or add a new declaration (.d.ts) file containing `declare module 'postcss-nesting';`ts(7016)
```

I then created a sibling file to `vite.config.ts` called `postcss-nesting.d.ts`:

```ts
declare module "postcss-nesting";
```

That _seems_ to resolve the problem, but it would be nice if this library included the necessary TypeScript definitions so developers don't have to do this. Also, I am unsure of whether my fix is actually a fix, or if I'll see things going wrong later.

FWIW, `postcss-nested` does have TypeScript definition files.

### Suggested solution

Include TypeScript definition files with the NPM package.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @nathan-alden-sr,

We are in the process of rewriting each plugin we maintain here in Typescript.
It will take a while before each plugin has been converted.

Contributions are always welcome :)

**Comment by romainmenke** [comment]
_re-open until release_

**Comment by romainmenke** [comment]
@nathan-alden-sr `postcss-nesting` 10.2.0 was just released and this version has TypeScript support. 

https://www.npmjs.com/package/postcss-nesting

Can you let us know if everything is working as expected now?
