### ISSUE TITLE
Missing error message in `postcss-trigonometric-functions`

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#605]
https://github.com/csstools/postcss-plugins/blob/936623bd6ea383bf7768878b645dc7c0f40597cc/plugins/postcss-trigonometric-functions/src/utils.ts#L240-L250

Is the empty `throw new Error()` intentional or should we add a message?

**Comment by Antonio-Laguna** [comment]
@romainmenke that's being caught below and nothing is done. I think there's value in adding it if you've seen behavior that's not clear there.
