### ISSUE TITLE
invalid selectors and CSS that is interpreted as an invalid selector throws exceptions

### ISSUE THREAD

**Issue by devingfx** [csstools/postcss-plugins#673]
### Bug description

The W3C spec says [@media rules can be nested](https://www.w3.org/TR/css-nesting-1/#conditionals) but this plugin craches when it find a nested @media

### Actual Behavior

```css
.my {
    @media print {
        color: red;
    }
}
```

`Error: Expected a pseudo-class or pseudo-element.`

### Expected Behavior

```css
@media print {
    .my {
        color: red;
    }
}
```

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

10

### What OS are you experiencing this on?

Linux

### Node Version

deno 1.27

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@devingfx Thank you for reaching out!

This just works on my end, but this might be related to deno vs node.

I have personally never pushed a new version for deno and I am unsure if anyone has done this beyond the initial release for deno.

I am also unable to verify if this works as intended or not with deno, I don't know anything about the deno ecosystem :/

**Comment by devingfx** [comment]
Hi! Thanks for the reply.
I wanted somewhat to check if this part of the spec is actually coded in the plugin as nothing is written on this in the readme...

Let me describe more precisely my deno pipeline (with reproductible install and versions) with the actual css file for you to reproduce the error...
(Or maybe could you indicate the right deno focussed repo to issue)
I'll make more tests also with a nodejs pipeline...
I'm not sure to be able to spend time quickly though, so let me get in touch asap!

**Comment by devingfx** [comment]
PS: One more thing: in my css @media is a custom media query, but this plugin is not deno ready so it's not configured in my pipeline!
Is it possible that the non transformation of this mq cause the error in postcss-nesting?

```css
.my {
    some-other: props here;
    @media (--mobile) {
        color: red;
    }
}
```

**Comment by romainmenke** [comment]
> Or maybe could you indicate the right deno focussed repo to issue

This is the right repo for that :)
But we only published a couple of versions specifically for deno.
In practice we don't have the capacity (time & knowledge) to really support deno.
We only actively support npm.

I have been hoping that native npm support in deno would take over.
https://deno.com/blog/v1.25#experimental-npm-support

When that becomes available you will be able to use the npm published package.

> Let me describe more precisely my deno pipeline (with reproductible install and versions) with the actual css file for you to reproduce the error...

That would be great! I am more than happy to look into it more then :)
Maybe there still is a bug somewhere in the latest npm version.

**Comment by devingfx** [comment]
> to really support deno
.. you only need to publish an es module version to be able to import it with `import name from 'https//unpkg.com/repo/themodule.js'`.
And of course be a pure JS code without nodejs api that postcss and plugins are allready!

**Comment by romainmenke** [comment]
> . you only need to publish an es module version to be able to import it with import name from 'https//unpkg.com/repo/themodule.js'.

This is already very different from what we have done in the past for `postcss-nesting` and this illustrates that it isn't a simple and unambiguous process :/

In the long term we will remove deno support and rely on deno itself to support npm packages. It just doesn't scale well for us to support deno. These plugins are maintained by volunteers so we have to be mindful of how much extra burden something creates.

At this time I am inclined to leave it broken.
Either I or another maintainer will have more time in the future or deno will start supporting npm packages.

**Comment by devingfx** [comment]
Okay :confounded: ! 
After further testing I could figure out that my nested CSS was lacking a `;` at the rule before the nested `@media` ... So it is not an actual bug, or problem with deno !
My bad! :confounded:

Maybe a better error message would help in this case though! ;)

Real code sample:

```CSS

.level {
	align-items: center;
	justify-content: space-between;
	
	/* Responsiveness */
	@media (--tablet) {
		& { 
			display: flex  /* Here is the missing ; */
			& > .level-item {
				&:not(.is-narrow) {
					flex-grow: 1
				}
			}
		}
	}
}

```

But the error message was pointing on the `.level {` line instead...

```bash
Error: Expected a pseudo-class or pseudo-element.
    at /home/***/dev/******/postcss/components/level.post.css:2:1
```

**Comment by romainmenke** [comment]
Thank you for this extra info @devingfx 🎉 

We can indeed give a more helpful message here.
What we should do is add `try catch` around each usage of the selector parser.
Then we can at least already give a message in this format :

```
"Failed to parse selector "display: flex & > .level-item" with message : "Expected a pseudo-class or pseudo-element.".
```

**Comment by devingfx** [comment]
Yes it would indeed be more helpfull!
I understand that the colon is causing the error speaking about pseudos and it may be difficult to spot the difference...

Thx very much!
(You can close this issue though)

**Comment by devingfx** [comment]
Also, I didn't read the code, but be carefull about the error because the spec says that ampersand have to be the first char and so in this case:

`display: flex & > .level-item` 

This have to be a spec error like "nested selector have to start with & or @nest"

Even with a `div:hover & > .level-item`...

**Comment by romainmenke** [comment]
>  the spec says that ampersand have to be the first char and so in this case

The specification has changed and selectors no longer need to start with `&`.
`@nest` was also removed from the specification. see : https://twitter.com/css_tools_/status/1587392697857413120

> This have to be a spec error like "nested selector have to start with & or `@nest`"

Ideally we would give specific errors, but the exceptions are thrown when the bit of text being processed can not be parsed as a selector.

If this happens we do not have anything to analyse the selector with and also can not give a more specific error than "failed to parse X with message Y".

We can only give warnings when a selector doesn't match the specification after the selector is successfully parsed.

**Comment by devingfx** [comment]
Okay! I didn't heared about this spec switch...
Thx

**Comment by romainmenke** [comment]
@devingfx We have updated as many plugins as possible so that they give a warning with more context instead an exception.

These new versions will be slow to rollout but they will all be included in the next upcoming major version of `postcss-preset-env`

**Comment by devingfx** [comment]
Thx!!!

How can I test this new errors? Do you have a commit/verision name plz?
Is it a change at postcss level? Or postcss-nesting level?

**Comment by romainmenke** [comment]
At the moment you can not test this.
It will take a while before all affected plugins have had a release.
We then also need to ship a new update of `postcss-preset-env` using those new plugin versions.

We are not going to ship a patch for all these plugins specifically for this issue because the root cause is invalid CSS and it is to much overhead for us.

It will roll out together with `postcss-preset-env` version `8`.
