### ISSUE TITLE
 has where-pseudo-class plugin?

### ISSUE THREAD

**Issue by J-env** [csstools/postcss-plugins#681]
### What would you want to propose?

```css
:where(:valid, :unsupported) {
  /* … */
}
```
output:
```css
:valid,
:unsupported {
  /* … */
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/:where#browser_compatibility

### Suggested solution

Probably close to this:
https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-is-pseudo-class

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
@J-env thanks for suggesting this. However, it is something we won't be tackling. `:where` has specificity purposes that can't be achieved by just removing the pseudo

**Comment by romainmenke** [comment]
see : https://github.com/csstools/postcss-plugins/discussions/509

Closing this for now because we can not create a good fallback.
