### ISSUE TITLE
Can we make CI faster without shooting ourselves in the foot too much?

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#685]
The current approach was nice in theory but something changed and now it is backfiring.

Current system :

1. build and test everything
2. cache build output
3. cache current commit hash

subsequent commits :

1. take commit hash from last ±10 commits
2. use those commit hashes as cache restore keys
3. restore cache with build outputs when available
4. check what changed since the last build was stored
5. build only those things
6. test only those things

I am assuming that this is going wrong because the cache mechanic in GitHub workflows is not intended for this.

- are the restored files not ok or complete in some way?
- are we sure there is no cache pollution between branches?

--------------

Another way to have a similar system is to store build outputs in git.
This has it's own negative aspects but maybe it also has benefits.

store build outputs in git :

pro's :

- git repo is a complete and functional archive
- easier to optimize CI
- unpkg and friends can read from the GitHub repo

con's :

- noisy commits
- git conflicts when multiple editors are working on the same plugin
- updating dependencies is more work (need to rebuild everything and push changed output files)

---------------

Are there other alternatives I am not thinking of?

**Comment by romainmenke** [comment]
_I always forget to explicitly mention this bit :_ 

A change to a plugin can affect `postcss-preset-env` or the `cli` package.
It is the major benefit of the monorepo. We can detect that a plugin change would be breaking for `postcss-preset-env` without needing to release it first.

This also means that we need to re-run the tests for `postcss-preset-env` and the `cli` each time a constituent plugin is altered.

To run those tests we need to have the contents of the `dist` folder for each constituent plugin.

Even when a change only concerns a single plugin we still need to build everything in the current setup.

Having a way to store the contents of the `dist` folder makes it possible to build and test subsets of the monorepo. Storing them in `git` is one such way.

**Comment by jonathantneal** [comment]
Does the monorepo currently have the ability to create iterative builds?

If so, could the compiled files be stored in a separate `dist` branch? If so, perhaps a GitHub action on commit could kick off the iterative build in that branch and then test against that?

**Comment by romainmenke** [comment]
> Does the monorepo currently have the ability to create iterative builds?

No :)

Storing `dist` files in `git` is one way to have this.

--

> If so, could the compiled files be stored in a separate dist branch?

Wouldn't this be very complex?
We would need a "dist" branch for `main` and for each feature branch that has sub branches.

We would also need automation to force push the exact write contents to these branches.
Which involves write-capable GitHub access tokens.

Can you link to an example implementation of such a setup?

**Comment by jonathantneal** [comment]
@romainmenke, thank you for your quick feedback, and for your patience with me. From these answers and the initial answers to my comment in the PR, I can understand why the option to include the dist files is being taken.

> Storing `dist` files in `git` is one way to have this.

Aye. I was trying to find a way to separate them from the main branch for development.

> Wouldn't this be very complex?

Yes. I would end up inventing a tool, and then never finishing the original tool. An example of that happening to me would be ... well, this project. 😅

> Which involves write-capable GitHub access tokens.

I might be working on such a feature for an unrelated project for Git CMS management, so it’s on me to present that AFTER its done. Again, I think I understand the issue much better now.

> Can you link to an example implementation of such a setup?

No, not yet. The onus is on me to prove it before I request it. I only wish it already existed. Also, I hope my feedback wasn’t too distracting.

---

Not that you need it, but you have my full support. Again, I just appreciate that you took the time to respond to my feedback in the PR, politely redirect me here, and then answer my questions here. ❤️

**Comment by romainmenke** [comment]
Yeah, I also wished this already existed as "off the shelf" :D

Our CI (work a.k.a. Mr. Henry) is capable of this.
But it is a very complex system that isn't exposed to 3rd party contributors and also can not be forked.

I want anyone to be able to fork this repo and allow them to edit and mutate it anyway they see fit.

---

https://github.com/romainmenke/gitattributes-playground/blob/main/.gitattributes

I also looked into `.gitattributes` but GitHub doesn't really support these :/
Marking the build output as binary and setting a different merge method would already make it much simpler to resolve merge conflicts.
