### ISSUE TITLE
[postcss-preset-env] selector list argument

### ISSUE THREAD

**Issue by kingyue737** [csstools/postcss-plugins#704]
### What would you want to propose?

https://caniuse.com/css-not-sel-list

Many old browsers do not support selector list argument of `:not()`.

### Suggested solution

Transpile list argument to single argument:

Before
```
:not(a, b, c)
```

After
```
:not(a):not(b):not(c)
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @kingyue737,

We have a plugin for exactly this case : https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md

[`not-pseudo-class`](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-selector-not#readme)

**Comment by kingyue737** [comment]
Strange, it does not take effect when I have a `chrome>68` in my browserslist config. I will investigate why. Thanks!

**Comment by romainmenke** [comment]
You're welcome!
