### ISSUE TITLE
postcss-nesting how to concatenate like sass

### ISSUE THREAD

**Issue by fallenturtle** [csstools/postcss-plugins#711]
Hi, I'm new to postcss and coming from sass. I'm trying to use plugins that are closer to what CSSWG draft and thus I chose this one. I'm trying to figure out how to do this:
```
.my-class {
  &__my-sub-class {
   color: red;
  }
}
```
to produce:
```
.my-class__my-sub-class {
   color: red;
}
```

But so far I'm failing. The closest I got was by adding postcss-current-selector, but it put things backwards, that is I would get:
``` 
__my-sub-class.my-class
```

Is it possible to get it like Sass, or do I need to switch to postcss-nested?

**Comment by Antonio-Laguna** [comment]
@fallenturtle thanks for reaching out!

Unfortunately, this usecase is not replicable within the CSSWG spec. You'd need to use `postcss-nested` as you hint if that's the type of syntax you're after.
