### ISSUE TITLE
Build fails with '[postcss-custom-media] "importFrom" is no longer supported'

### ISSUE THREAD

**Issue by tvsbrent** [csstools/postcss-plugins#725]
### Bug description

With an upgrade to `postcss-custom-media` version 9.x, we began seeing this error in our builds:

```
Loading PostCSS "postcss-custom-media" plugin failed: [postcss-custom-media] "importFrom" is no longer supported
```

I do see there is a [discussion about removing support for `importFrom` and `exportTo`](https://github.com/csstools/postcss-plugins/discussions/192), but it didn't look like that discussion was resolved to the point where the change as being made. Also, I the `README` and `CHANGELOG` in the project have not been updated for version 9.x, so I'm wondering if the release of that functionality was intentional.

### What plugin are you experiencing this issue on?

PostCSS Custom Media Queries

### Plugin version

9.0.1

### Node Version

18.12.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
This was intentional.

see : https://github.com/csstools/postcss-plugins/issues/461
that issue is also pinned to make it more visible.

It leads you to https://github.com/csstools/postcss-plugins/blob/postcss-preset-env--v8/plugins/postcss-custom-media/CHANGELOG.md#900-november-14-2022

**Comment by romainmenke** [comment]
relevant : https://github.com/csstools/postcss-plugins/pull/717

https://github.com/csstools/postcss-plugins/blob/f1ea5991f0c1b2e909706b14b02e0447ba108f25/plugins/postcss-design-tokens/README.md#postcss-design-tokens-

After that change you will be able to use our design tokens plugin to inject values into at rules.

```json
{
  "foo": { "value": "(min-width: 768px)" }
}
```

```css
@design-tokens url('./tokens.json') format('style-dictionary3');

@custom-media --foo design-token('foo');
```

**Comment by tvsbrent** [comment]
Thank you for the information!

Perhaps an update could be made to the `package.json` to point at the new documentation? For example, we use "renovate" to update our dependencies, and I think due to the configuration found in the `package.json`, it didn't lead to the new docs. And for whatever reason, my googling failed when searching for the issue, which led to posting this issue.

**Comment by romainmenke** [comment]
Totally fine and thank you for opening the issue :)
It's important that we get enough feedback that the current situation is confusing.

We only have one more round of changes planned before this is all merged into the main branch.

So I am currently hoping that we don't have to update and re-release each plugin because that would also mean that we would have to change it back en ship new releases after merging.

For now I think it is fine if people open issues when they don't find what they are looking for.
