### ISSUE TITLE
`:has` pseudo selector not working properly on hover

### ISSUE THREAD

**Issue by nlhkabu** [csstools/postcss-plugins#750]
### Bug description

I have an interface where I have items nested inside other items.

Each item has a handle for drag and drop (on the left) and a menu (on the right).

i want to show the handle and menu on hover, but only for the item that I am directly hovering on, **not** it's parent (or parents)

This is working well on Chrome (without polyfill):

![Screenshot from 2022-12-12 11-06-10](https://user-images.githubusercontent.com/3323703/207030360-d833b199-b886-4a81-a97c-0e95c0d4e98f.png)

But this is what I get with Firefox (107):
![Screenshot from 2022-12-12 11-06-09](https://user-images.githubusercontent.com/3323703/207030390-60f7fd7b-1809-4086-880e-035f3053bc56.png)

My setup

package.json
```
"postcss-preset-env": "8.0.0-alpha.1",
```

index.html
```
<script src="https://unpkg.com/css-has-pseudo@4.0.1/dist/browser-global.js"></script>
<script>cssHasPseudo(document)</script>
```

postcss.config.js
```
const postcssPresetEnv = require("postcss-preset-env");

module.exports = {
  plugins: [
    postcssPresetEnv({
      features: {
        "nesting-rules": true,
        "has-pseudo-class": true,
      },
    }),
  ],
};
```

### Source CSS
```
.draggable:hover:not(:has(.nested-list:hover)) {
  & > .entry .grabber {
    display: flex;
  }

  & > .entry .entry-menu {
    display: inline;
  }
}
```

### Expected CSS

??

### Actual CSS

??

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

N/A

### What plugin are you experiencing this issue on?

CSS Has Pseudo

### Plugin version

8.0.0-alpha.1

### What OS are you experiencing this on?

Linux

### Node Version

v16.15.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@nlhkabu Do you also have an html snippet we could use to test with?

**Comment by nlhkabu** [comment]
@romainmenke here you go:
```html
<div class="draggable" role="listitem" >
    <div class="entry">
        <span class="grabber"></span>
        <span class="bullet">⏷</span>
        <div class="content">
            <p>Rowed 45 minutes</p>
        </div>
        <div class="entry-menu"></div>
    </div>
    <div class="entry-list nested-list" role="list">
        <div class="draggable" role="listitem" >
            <div class="entry">
                <span class="grabber"></span>
                <span class="bullet">•</span>
                <div class="content">
                    <p>Rowed 20 minutes</p>
                </div>
                <div class="entry-menu"></div>
            </div>
        </div>
        <div class="draggable" role="listitem" >
            <div class="entry">
                <span class="grabber"></span>
                <span class="bullet">•</span>
                <div class="content">
                    <p>Rowed 25 minutes</p>
                </div>
                <div class="entry-menu"></div>
            </div>
        </div>
    </div>
</div>
```

**Comment by romainmenke** [comment]
@nlhkabu We have just released `v4.0.2` : https://www.npmjs.com/package/css-has-pseudo
Can you check that version to see if your issue is resolved?

**Comment by romainmenke** [comment]
Just to make sure I also made two codepens :
- native without any polyfill or postcss : https://codepen.io/romainmenke/pen/xxzoRoG
- for older browsers : https://codepen.io/romainmenke/pen/yLEdgyw

There was one thing I forgot to mention before.
You also need to enable certain watchers :
- `:hover`
- specific attributes

https://www.npmjs.com/package/css-has-pseudo#:~:text=Internet%20Explorer%209.-,Browser%20Usage,-hover

```html
<script>cssHasPseudo(document, { hover: true })</script>
```

With the latest version and the setting I can no longer spot a difference between the native behavior and the polyfill.

**Comment by nlhkabu** [comment]
Thanks @romainmenke 

I added `{ hover: true }` and this has solved my problem, using `"postcss-preset-env": "8.0.0-alpha.1"` and version `4.0.1` of the broswer polyfill.

Thanks again! :tada: :rocket:
