### ISSUE TITLE
[DX]: Add better description to `csstools/postcss-preset-env`

### ISSUE THREAD

**Issue by dpschen** [csstools/postcss-plugins#753]
I often get to this repo by [search Google for 'postcss-preset-env'](https://www.google.com/search?q=postcss-preset-env).
The first result there is [the deprecate repo](https://github.com/csstools/postcss-preset-env).

I'm not sure how the Google ranking could be improved, but it would be helpful if you would not just archive the old repos but also make the new repo easier reachable, by editing the description in the sidebar so that the link points to the package in the subdirectory in the new mono repo:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/6173598/207594855-b1f79ef7-78e3-495e-bc96-e48abfbe3161.png">

*Description as it is now*

=> Edit description and change link to:

> `https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env`

**Comment by Antonio-Laguna** [comment]
@dpschen thanks for pointing that out, it also contained the legacy URL which we had to migrate afterward. I've updated that description now!

**Comment by dpschen** [comment]
Perfect, thanks!
