### ISSUE TITLE
`react-app-rewire-postcss` seems abandoned

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#777]
https://github.com/csstools/react-app-rewire-postcss

This is outdated and people are having issues because of it.
We are however still linking to it from our install docs.

We need to either fix that package or remove it from the docs.

**Comment by romainmenke** [comment]
CRA goes through great lengths to prevent users from customizing any config.
We should not provide hacks to work around this.

- If the community wants custom configs they should not be using CRA.
- If the community wants to use CRA and have custom PostCSS configs they should take that up with the CRA authors.

By providing and advising hacks we are not really helping anyone.
The end result will never be a solid and dependable stack.

I've removed any and all references to CRA from our documentation.

I suggest we archive this repo and deprecate the npm package : https://github.com/csstools/react-app-rewire-postcss

---

Today there are also so many meta frameworks that do allow users to customize configs.
I think they are more interesting for users that want something like CRA but also want to customize.

**Comment by Antonio-Laguna** [comment]
@romainmenke this has been archived and the package deprecated on npm!

Closing this as it's completed

**Comment by briskteq-faiz** [comment]
what is the alternative for that library?

**Comment by romainmenke** [comment]
Hi @briskteq-faiz,

There is no alternative.
CRA is hostile towards customizing config and setup details.
Maintaining packages that try to add this anyway is a losing battle :/

The best thing you can do is to pick stacks and meta frameworks which are open and allow you to customize.

**Comment by briskteq-faiz** [comment]
okay thanks for that 👍
