### ISSUE TITLE
Release of `css-tokenizer` and related packages

### ISSUE THREAD

**Issue by romainmenke** [csstools/postcss-plugins#790]
These need to be done in sequence and one by one :

- [x] `css-tokenizer` release version 2
- [x] `css-parser-algorithms` update peer dependencies
- [x] `css-parser-algorithms` release version 2
- [x] `media-query-list-parser` update peer dependencies
- [x] `media-query-list-parser` release version 2
- [x] `cascade-layer-name-parser` update peer dependencies
- [x] `cascade-layer-name-parser` release version 2

----

Also up for a release :

- `selector-specificity` (`v2.1.0`)

**Comment by Antonio-Laguna** [comment]
This is all live now!

**Comment by romainmenke** [comment]
Thank you so much for this 🙇
