### ISSUE TITLE
This version of postcss-preset-env is not optimised to work with PostCSS 8.   │ │                Please update to version 7 of PostCSS Preset Env.  

### ISSUE THREAD

**Issue by w-danboard** [csstools/postcss-plugins#817]
### What would you want to propose?

This version of postcss-preset-env is not optimised to work with PostCSS 8.   │
│                Please update to version 7 of PostCSS Preset Env.  

### Suggested solution

This version of postcss-preset-env is not optimised to work with PostCSS 8.   │
│                Please update to version 7 of PostCSS Preset Env.  

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
@w-danboard thanks for reaching out. I'm not sure what is the actual issue you're reporting given that the Suggested Solution matches completely "What you want to propose"

That message is shown to users of PostCSS Preset Env 6.7.1. Are you having issues with the upgrade perhaps?

**Comment by romainmenke** [comment]
Closing for now.

@w-danboard Feel free to provide more info, then we will re-open this issue 🙇
