### ISSUE TITLE
Breaking change in v11.0.0 (TypeError: postcssCustomProperties.process is not a function)

### ISSUE THREAD

**Issue by nolimitdev** [csstools/postcss-plugins#83]
By doc in v12.0.0 https://www.npmjs.com/package/postcss-custom-properties/v/12.0.0 it was possible to use `postcss-custom-properties` directly 

```
const postcssCustomProperties = require('postcss-custom-properties');
postcssCustomProperties.process(YOUR_CSS /*, processOptions, pluginOptions */);
```

Now by doc in minor v12.0.1 https://www.npmjs.com/package/postcss-custom-properties/v/12.0.1 it is not possbile and postcssCustomProperties.process() does not work any more. This is breaking change in minor release (v12.0.1 should be v13.0.0) and without any mention in changelog https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-custom-properties/CHANGELOG.md#1201-december-16-2021

Why this change please? Could be `postcssCustomProperties.process()` working back?

**Comment by romainmenke** [comment]
Hi @nolimitdev,

This was removed in v11.0.0, the last version with support for this API was v10.0.0

This change was introduced here : https://github.com/postcss/postcss-custom-properties/pull/229

v12.0.1 only updated the outdated documentation.

-----

This API was removed because PostCSS v8 made it impossible.

**Comment by nolimitdev** [comment]
UPDATE: It seems tht breaking change was between v10.0.0 and v11.0.0 withou metnion here https://github.com/csstools/postcss-plugins/blob/main/plugins/postcss-custom-properties/CHANGELOG.md#1100-january-12-2021 and doc example with `postcssCustomProperties.process` was not updated until v12.0.1
