### ISSUE TITLE
`preserve: true` does not preserve logical properties

### ISSUE THREAD

**Issue by kmonahan** [csstools/postcss-plugins#863]
### Bug description

When configuring `postcss-preset-env` with `preserve: true` either for the specific feature or globally, my pre-polyfilled CSS is still removed and replaced with the polyfilled version. Since logical properties have at least some browser support, I would like to add the polyfilled version as a fallback rather than replacement.

**PostCSS Config**
```
features: {
  'float-clear-logical-values': {
    preserve: true,
  },
  'logical-properties-and-values': {
    preserve: true,
  },
},
```

I'm able to reproduce the same behavior on CodePen: https://codepen.io/kjmonahan/pen/abaOGmB

### Source CSS

```
border-inline-end: 1px solid var(--ui-border);
display: block;
float: inline-start;
margin-inline-end: 0.75em;
padding-inline-start: 0;
padding-inline-end: 0.75em;
```

### Expected CSS

```
border-right: 1px solid var(--ui-border);
border-inline-end: 1px solid var(--ui-border);
display: block;
float: left;
float: inline-start;
margin-right: 0.75em;
margin-inline-end: 0.75em;
padding-left: 0;
padding-inline-start: 0;
padding-right: 0;
padding-inline-end: 0.75em;
```

### Actual CSS

```
border-right 1px solid var(--ui-border);
display: block;
float: left;
margin-right: 0.75em;
padding-left: 0;
padding-right: 0;
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### What plugin are you experiencing this issue on?

PostCSS Logical, PostCSS Logical Float and Clear

### Plugin version

6.0.1

### Node Version

16.18.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by kmonahan** [comment]
Using v8.0.1 of postcss-preset-env, v6.0.1 of postcss-logical and v1.0.1 of @csstools/postcss-logical-float-and-clear

**Comment by Antonio-Laguna** [comment]
@kmonahan this is actually intentional. That option does not exist in any of the logical plugins. That’s because the fallback might not mean the same as the transformed depending on the user

**Comment by romainmenke** [comment]
@kmonahan Did you have any further questions about this?
If not, I think we can close this?
