### ISSUE TITLE
Sites link in readme leads to 404 page

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [csstools/postcss-plugins#876]
The [sites](https://github.com/csstools/postcss-plugins/sites) link in the [readme](https://github.com/csstools/postcss-plugins/blob/main/README.md) doesn't work. Where is it meant to go? :)

I guess [this](https://preset-env.cssdb.org) is the website and [this](https://github.com/csstools/postcss-plugins/tree/main/sites/postcss-preset-env) is the source code for it - but I couldn't find any actual links to the website (other than via Google).

**Comment by romainmenke** [comment]
Thank you @ehoogeveen-medweb for reporting this.
I've fixed the link in the general readme.

----

>  but I couldn't find any actual links to the website 

It is linked here :

<img width="405" alt="Screenshot 2023-02-21 at 22 59 51" src="https://user-images.githubusercontent.com/11521496/220468357-c9396d3c-5b5f-41b4-95d7-3c51b5f6f743.png">

**Comment by ehoogeveen-medweb** [comment]
Ah! Of course, that makes sense. I guess I got too focused on the readme. Thanks for fixing the link!
