### ISSUE TITLE
Unable to load custom media with postcss-preset-env

### ISSUE THREAD

**Issue by jnlsn** [csstools/postcss-plugins#883]
### Reproduction link

https://replit.com/@jaynlsn/PostCSS-Custom-Media-Crash?v=1

### Bug description

I'm getting an `Invalid or unexpected token` error when attempting to load custom media using the new recommended approach with postcss-global-data.

### Actual Behavior

Try to run the replit dev server and you will get an `invalid or unexpected token` error when postcss tries to load the custom-media file.

### Expected Behavior

Dev server loads.

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Extra config

```
module.exports = {
  plugins: [
    "postcss-flexbugs-fixes",
    [
      "postcss-global-data",
      {
        files: [
          require("./styles/custom-media.css").resolve(),
        ],
      },
    ],
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 0,
        preserve: false,
        features: {
          "custom-properties": false,
        },
      },
    ],
  ],
};
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

8.0.1

### What OS are you experiencing this on?

Linux

### Node Version

18

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by jnlsn** [comment]
In the actual repo that I'm trying to implement this in, I need to load the custom media queries from another package. e.g. `require('@design-system/tokens/css/custom-media.css')` Shouldn't require.resolve() just return the path name?

**Comment by jnlsn** [comment]
Oooh! sorry false alarm. It should be `require.resolve()` 🤦 Thanks for looking at this!

**Comment by romainmenke** [comment]
Always happy to help 😄
