### ISSUE TITLE
Nesting not polyfilled

### ISSUE THREAD

**Issue by privatenumber** [csstools/postcss-plugins#886]
### Bug description

`postcss-nesting` isn't enabled, even with stage set to 4.

### Source CSS

```css
.hello {
	color: red;

	&.world {
		color: blue;
	}
}
```

### Expected CSS

```css
.hello {
	color: red;
}
.hello.world {
		color: blue;
	}
```

### Actual CSS

```css
.hello {
	color: red;

	&.world {
		color: blue;
	}
}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Extra config

```js
const postcssPresetEnv = require('postcss-preset-env');

module.exports = {
	plugins: [
		postcssPresetEnv({
			"browsers": [
				"> 0.2% and not dead"
			],
			"stage": 4
		})
	]
}
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

8.0.1

### What OS are you experiencing this on?

macOS

### Node Version

v18.7.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

----

I also verified on https://preset-env.cssdb.org/playground/
Would be nice if the preset-env version could be listed there. I'm unsure if it's up to date.

**Comment by romainmenke** [comment]
Hi @privatenumber,

Can you try with `1` instead of `4`?
At lower number you will get less stable, but more features.

<img width="385" alt="Screenshot 2023-03-09 at 08 12 59" src="https://user-images.githubusercontent.com/11521496/223947702-2e38c3fb-073f-4155-8378-3dfe596cccf3.png">

**Comment by privatenumber** [comment]
> But you might not be ok with the super experimental features from stage 0.

I see. In my case, nested CSS syntax was left untransformed and broke the styling. So I thought `post-preset-env` was interpreting it as "ignore it because your configured browsers support it" rather than "ignore it because your config doesn't enable the polyfill".

I think the DX can be improved by clarifying the behavior the docs. Or by outputting a warning for Stage 2~0 features if it's used but not polyfilled. Perhaps this would be a PostCSS level concern as it should parse syntax based on the CSS spec version (e.g. as determined by browserslist).

> It is debatable that this should have been a set and not a range.

I like that and I agree it's more intuitive. I think it can still be supported without breaking change as `stage` doesn't accept an array yet. 👍

> Setting the stage option affects your exposure to spec changes.

This explanation makes a lot of sense and I think it's worth adding this to the doc. 👍

> They do different things and I am ok with where and how they are current documented.

FWIW, I've been using `postcss-preset-env` since 2017 and this has always confused me. To clarify, you wouldn't be open to any improvements in the docs? Would it be a waste of my time if I tried?

> The default is that both are set. Stage is 2 and browsers is the browserslist default.

Is there a way to turn off the `stage` feature and only look at browserslist? As a casual user, I'm not aware of all the features and stages, and just want my CSS to work on the browsers I target.

Going back to the previous example, I can't seem to find a way where I can polyfill nesting but preserve `all: initial`:
```css
.hello {
  all: initial;

  &.world {
    color: blue;
  }
}
```

If you'd like to see my code, I'm [testing on StackBlitz](https://stackblitz.com/edit/node-2bkxbk?file=index.js).

**Comment by privatenumber** [comment]
Gotcha, thanks so much again for your patience and thoughtful responses.

`stage: 0` seemed to do the trick! I also think this is worth documenting as a way to turn of `stage` and defer all configuration to browserslist.

I haven't tried the debug flag, but will try it out on the larger project tomorrow.

I will think about this deeper and open a PR to improve the docs concisely if I have any ideas.

**Comment by rschristian** [comment]
Is there a way to correct this without using `postcss-preset-env`?
