### ISSUE TITLE
Reverse postcss-nesting

### ISSUE THREAD

**Issue by tbondwilkinson** [csstools/postcss-plugins#913]
### What would you want to propose?

I'm interested in postcss plugin that does the inverse of postcss-nesting.

The existing postcss-nesting goes from CSS nesting to vanilla CSS, but I'm interested in going from vanilla CSS to nesting CSS as an optimization to reduce bytes on browsers that support nesting CSS. I'm interested to see if this reduces bytes.

### Suggested solution

An optimizer that finds CSS that can be nested.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @tbondwilkinson!

This request might be a good fit for a project like cssnano : https://github.com/cssnano/cssnano

That project focusses on minification and optimizing CSS sources.

Our focus is on producing CSS that works in as many browsers as possible.
Transforming to CSS that only works in modern browsers is outside of our scope :)

**Comment by tbondwilkinson** [comment]
Cool I'll ask over there :)
