### ISSUE TITLE
using color-mix causes "TypeError: t.replaceComponentValues is not a function"

### ISSUE THREAD

**Issue by fallenturtle** [csstools/postcss-plugins#930]
I'm running postcss 8.4.21 through yarn v3 and using postcss-preset-env 8.3.0. When I try to use:
background-color: color-mix(in lch, purple 50%, plum 50%);

and run yarn i see this error in the output and the target file is not compiled:
TypeError: t.replaceComponentValues is not a function

**Comment by romainmenke** [comment]
Can you try updating transient dependencies?
It seems like yarn isn't updating dependencies of dependencies correctly in your case.

**Comment by romainmenke** [comment]
We will rollout a patch with updated dependency versions listed in package.json.
But in the meantime you can work around this by updating transitive dependencies manually.

**Comment by romainmenke** [comment]
@fallenturtle This issue should be resolved now.
Can you try updating to the latest version of the postcss plugins you are using?

**Comment by fallenturtle** [comment]
It's working now. Thanks!

**Comment by romainmenke** [comment]
Thank you for reporting this!
