### ISSUE TITLE
Support overflow-block/overflow-inline

### ISSUE THREAD

**Issue by thewilkybarkid** [csstools/postcss-plugins#946]
### What would you want to propose?

The [CSS Overflow Module Level 3](https://drafts.csswg.org/css-overflow-3/) draft introduces logical equivalents of `overflow-x` and `overflow-y`: `overflow-block` and `overflow-inline`.

### Suggested solution

Turn `overflow-block` and `overflow-inline` into `overflow-x` and `overflow-y` as appropriate like other logical properties.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
- `overflow-inline` mdn : https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-inline#browser_compatibility
- `overflow-block` mdn : https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-block#browser_compatibility

- wpt : https://wpt.fyi/results/css/css-overflow/logical-overflow-001.html?label=master&label=experimental&aligned&q=logical

**Comment by romainmenke** [comment]
Currently not supported/handled :
- "overflow-block"  has different release dates and was unhandled
- "overflow-inline"  has different release dates and was unhandled
- "overscroll-behavior-block"  has different release dates and was unhandled
- "overscroll-behavior-inline"  has different release dates and was unhandled
- "scroll-margin-block-end"  has different release dates and was unhandled
- "scroll-margin-block-start"  has different release dates and was unhandled
- "scroll-margin-inline-end"  has different release dates and was unhandled
- "scroll-margin-inline-start"  has different release dates and was unhandled
- "scroll-padding-block-end"  has different release dates and was unhandled
- "scroll-padding-block-start"  has different release dates and was unhandled
- "scroll-padding-inline-end"  has different release dates and was unhandled
- "scroll-padding-inline-start"  has different release dates and was unhandled

**Comment by romainmenke** [comment]
Hi @thewilkybarkid,

This has been added in `postcss-preset-env` `v9.3.0`.

You can try it out here : https://preset-env.cssdb.org/playground/#JTdCJTIyc291cmNlJTIyJTNBJTIyJTIzZGl2MSUyMCU3QiU1Q24lMjAlMjBvdmVyZmxvdy1pbmxpbmUlM0ElMjBoaWRkZW4lM0IlNUNuJTdEJTIyJTJDJTIyY29uZmlnJTIyJTNBJTdCJTIyYnJvd3NlcnMlMjIlM0ElNUIlMjIlM0UlMjAwLjIlMjUlMjBhbmQlMjBub3QlMjBkZWFkJTIyJTVEJTJDJTIybWluaW11bVZlbmRvckltcGxlbWVudGF0aW9ucyUyMiUzQTAlMkMlMjJzdGFnZSUyMiUzQTIlMkMlMjJsb2dpY2FsJTIyJTNBJTdCJTIyaW5saW5lRGlyZWN0aW9uJTIyJTNBJTIybGVmdC10by1yaWdodCUyMiUyQyUyMmJsb2NrRGlyZWN0aW9uJTIyJTNBJTIydG9wLXRvLWJvdHRvbSUyMiU3RCUyQyUyMmZlYXR1cmVzJTIyJTNBJTdCJTIybmVzdGluZy1ydWxlcyUyMiUzQSU3QiUyMm5vSXNQc2V1ZG9TZWxlY3RvciUyMiUzQWZhbHNlJTdEJTdEJTdEJTdE
