### ISSUE TITLE
Add logical fallback for padding and margin

### ISSUE THREAD

**Issue by Th3S4mur41** [csstools/postcss-plugins#960]
### What would you want to propose?

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) `margin` and `padding` are considered experimental and are not yet properly interpreted by various browsers as logical properties.

This lead tools like stylelint to suggest using the `*-block` and `*-inline instead`
https://github.com/Jordan-Hall/stylelint-use-logical-spec/issues/39

### Suggested solution

Instead of changing the code until browser support gets better, it would be great if we could keep using the shorthand and have [postcss-logical](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical) replace them through the longer variations in the production CSS

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
@Th3S4mur41 Thank you for reaching out about this.

Unfortunately I don't quite understand what you mean here.
`margin` and `padding` are definitely not experimental and also not listed as such on MDN.

The experimental labeling is for the `logical` keyword.
<img width="326" alt="Screenshot 2023-05-04 at 16 56 28" src="https://user-images.githubusercontent.com/11521496/236246626-3b8b3d7d-9a1a-4cc0-b6ad-452ef77cbfc7.png">

What would help me to understand the issue better is to see example CSS.
In the linked issue (https://github.com/Jordan-Hall/stylelint-use-logical-spec/issues/39) you also do not provide any example CSS, only an error message.

**Comment by romainmenke** [comment]
**for context**

The `logical` keyword is pretty much dead.
There is very little chance that any browser will ever implement.

At one time it was considered to add support for :
`margin: 10px 5px logical;`

Which would then expand to logical properties instead of physical properties.  
Without the `logical` keyword `margin` always corresponds to physical properties.

-----

New information or insights can unblock this and can bring back this `logical` keyword.
But that should be brought to the CSSWG (the spec editors)

**Comment by Th3S4mur41** [comment]
@romainmenke thanks for the detailed explanation.
So if I get it right, that means that without the `logical` keyword, using the shorthand with two values will always make the browser interpret them as physical properties.

Therefor the suggestion from [stylelint](https://github.com/Jordan-Hall/stylelint-use-logical-spec/pull/24), to rather use the combination of `*-block` and `*-inline` instead is correct if you want to take advantage of the "logical" directions.
Right?

**Comment by Th3S4mur41** [comment]
Got it, thanks a lot. 
It's much clearer now 👍
