### ISSUE TITLE
Swap CC0-1.0 licenses for MIT-0 licenses

### ISSUE THREAD

**Issue by jonathantneal** [csstools/postcss-plugins#965]
### What would you want to propose?

I believe some of the projects in this repository can switch to a license that is more inclusive to the OSS community.

But first, thank you. Especially thank you to @Antonio-Laguna and @romainmenke. You have successfully maintained PostCSS Preset Env and brought the entire PostCSS ecosystem to a much higher standard of quality. There were quite a few issues that needed to be resolved when you all started — namely the upgrade to the PostCSS visitor API — and you overcame every obstacle then and since. You know this already, but let me say it out loud; this is really your project, and I’ve become more of an observer. With that in mind, I hope you’ll consider this suggestion as a former maintainer who holds some responsibility for the license.

I think my decision to use the **CC0 1.0 Universal (CC0 1.0) Public Domain Dedication** license in all of my work may have been an unaddresed issue. As a non-OSI Approved license, this has been a hindrance to some companies and to some areas of the world. Even recently, I noticed that a requirement to include a plugin in [the postcss plugins directory](https://github.com/csstools/postcss-plugins-directory) is that the plugin use an OSI Approved License. I’ve seen similar requirements elsewhere.

I used CC0-1.0 because I have always wanted to allow absolutely anyone to do what they want with my code, however they see fit and wherever they find themselves. In my first year in tech, I observed a nasty licensing debacle over jQuery’s dual MIT and GPL licenses. I wanted nothing to do with MIT, GPL, or any license that might put a barrier between my work and those who might benefit from it. That was a long time ago, but if those issues are still real and still exist anywhere, then I still feel the same way.

While CC0-1.0 was intended to circumvent licensing issues, the reality is that it did not. CC0-1.0 never became an OSI Approved License. I’ve been told that the CC0 license has issues in countries where a ‘public domain’ does not exist. I have also been receiving emails every few months for the last half-dozen years from various companies who run into legal issues with CC0-1.0, and who require my explicit approval to use my code with that license. Sadly, I must admit that I now often forget to provide that permission, which makes me a hypocrite of all my intentions.

In order to reduce any obstacles to this successful project, I think we should change all **CC0-1.0** licenses to an OSI approved license, in order to conform the higher standards you’ve established, and to improve the reach of these tools to all people.

### Suggested solution

I believe there is now a better licensing solution than CC0-1.0; the **MIT No Attribution License (MIT-0)**. **MIT-0** is an [OSI Approved License](https://opensource.org/license/mit-0/) that provides the offers the most trusted **MIT** license without the cost of attribution.

You should know that the CC0-1.0 license is so permissive that you could have already dropped it for another license. I have witnessed folks fork other CC0 code of mine and immediately change the license to MIT before (_Hi, Astro! You made the WebAPI project so much better, and I love you!_). I wonder; did you keep it around for my sake? If so, thank you for letting that software remain free of any constraints, even attribution.

Switching to MIT-0 would be in line with my intentions for using CC0-1.0 in the first place. I am happy to perform the commit, if it helps reduce your work, or if it matters as a kind of seal of approval.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [X] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment]
Hi all!

Loving the sentiment and also the carefulness in every part of this process!

I think your plan makes sense to me @romainmenke. I don't think people often relicense because they don't care as much, we know people that go the other way around and most people don't care such as BlueOak...

It's only impactful for those companies closely following licenses and such so I'm all in for the change and make a sensible plan for moving it!

**Comment by romainmenke** [comment]
`8.5.0` has been out for about a week and we haven't received any bug reports.
There aren't any open issues or feature requests that have any urgency.

If everyone agrees, now might be a good time to make this switch?

----

Plan would be :

- change the License to `MIT-0` for all packages
- add a changelog entry in all packages
- do a release of everything
- do a blog post
- wait ±2 weeks before doing further feature work

**Comment by romainmenke** [comment]
Blog post : https://github.com/csstools/postcss-plugins/pull/1009

@jonathantneal Please let us know if there is anything you would like to change here.

The blog post is only intended to be a communication tool.
Something we can share and link to.

The full thought process is best documented here, on GitHub.

**Comment by jonathantneal** [comment]
Looking now. Y’all rock!

**Comment by jonathantneal** [comment]
That was great. Thank you so much. Fellows, one day I’m gonna be a developer like y’all, and I hope to contribute back to this project. You’ve done such an amazing job. I barely keep up with a few emails a week, but I know I’m getting better every day. Y’all are creating novels each week, and being so responsible with OSS. I was really scared to turn the project at first, but truly I have learned it is I who want to learn how to OSS like you.

**Comment by romainmenke** [comment]
Thank you for that Jon, don't forget that you started all this and lead this project for many years ;)

I've prepared the license changes itself here :
https://github.com/csstools/postcss-plugins/pull/1011

It would awesome if you could go over those aswel 🙇

**Comment by romainmenke** [comment]
A week has passed and we have received no feedback on this change.
I am assuming that this will have been visible to enough people thanks to tools like Dependabot.

I think it's fine to continue feature work at this point.
