### ISSUE TITLE
`postcss-preset-env` throws TypeError starting with v8

### ISSUE THREAD

**Issue by ERuseckas** [csstools/postcss-plugins#969]
### Bug description

v7.8.3 is working fine, but all the v8 versions are giving me the same error:

```
[!] (plugin postcss) TypeError: o is not a function
src/global.pcss
TypeError: o is not a function
    at /node_modules/postcss-preset-env/dist/index.cjs:1:17553
    at Array.forEach (<anonymous>)
    at pluginIdHelp (/node_modules/postcss-preset-env/dist/index.cjs:1:17429)
    at OnceExit (//node_modules/postcss-preset-env/dist/index.cjs:1:18705)
    at LazyResult.runAsync (/node_modules/postcss/lib/lazy-result.js:433:21)
```

This error is thrown even if my used `src/global.pcss` file is completely empty.

### Can you reproduce it with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

None

### Extra config

my used postcss config
```js
                require('postcss-discard-comments')(),
		require('stylelint')({
			files: 'src/**/*.pcss',
			cache: true,
			cacheLocation: path.resolve(__dirname, 'node_modules/.cache/.stylelintcache')
		}),
		require('postcss-mixins')({
			mixinsFiles: path.resolve(__dirname, 'src/common.pcss')
		}),
		require('postcss-preset-env')({
			stage: 2,
			preserve: false,
			features: {
				'custom-media-queries': true,
				'custom-properties': false,
				'custom-selectors': true,
				'environment-variables': true
			}
		}),
		require('postcss-nested')(),
		require('postcss-discard-empty')(),
		require('postcss-reporter')({ clearReportedMessages: true })
```

versions:
```json
                "postcss": "^8.4.23",
		"postcss-discard-comments": "^6.0.0",
		"postcss-discard-empty": "^6.0.0",
		"postcss-mixins": "^9.0.4",
		"postcss-nested": "^6.0.1",
		"postcss-preset-env": "^8.3.2",
		"postcss-reporter": "^7.0.5",
		"stylelint": "^15.3.0"
```

it's running under `rollup` v2 by using latest `rollup-plugin-postcss`:
```js
        postcss({
		extract: path.resolve('dist/main.min.css'),
		minimize: true
	})
```

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

8.*.*

### What OS are you experiencing this on?

macOS

### Node Version

18.3.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment]
Hi @ERuseckas,

Thank you for reaching out about this!

Can you remove `'environment-variables': true` from your config?
I think that should make the error go away.

https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/CHANGELOG.md#800-january-24-2023

From the changelog : 

> Removed `postcss-env-function` (breaking).

If you depend on this feature you must add it separately as a dependency in `package.json` and in your PostCSS config :

```
		require('postcss-mixins')({
			mixinsFiles: path.resolve(__dirname, 'src/common.pcss')
		}),
		require('postcss-env-function')(),
		require('postcss-preset-env')({
			stage: 2,
			preserve: false,
			features: {
				'custom-media-queries': true,
				'custom-properties': false,
				'custom-selectors': true,
				'environment-variables': true
			}
		}),
		require('postcss-nested')(),
```

------------

We will roll out a patch shortly to ensure this exception doesn't happen.

**Comment by ERuseckas** [comment]
Thank you @romainmenke 
Removing that line helped

**Comment by romainmenke** [comment]
@ERuseckas This exception has also been resolved in the latest release of `postcss-preset-env`. If you encounter a similar case the plugin will give you more useful feedback on what is going on.

Thank you again for reporting this!
